wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: batch/batch_step
      6:
      - 3
    - 1: batch/loss
      5: 1
      6:
      - 1
    - 1: batch/accuracy
      5: 1
      6:
      - 1
    - 1: batch/learning_rate
      5: 1
      6:
      - 1
    python_version: 3.9.6
    start_time: 1672943301.843173
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 7
      - 23
      - 37
      - 38
      - 39
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_3:
  desc: null
  value: relu
activation_4:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 32
decay_rate:
  desc: null
  value: 0.4876120565003881
decay_steps:
  desc: null
  value: 506
dense1_size:
  desc: null
  value: 81
dense2_size:
  desc: null
  value: 33
dropout:
  desc: null
  value: 0.2857542235053987
epoch:
  desc: null
  value: 8
initial_learning_rate:
  desc: null
  value: 0.000449030742879449
log_freq:
  desc: null
  value: 2
loss:
  desc: null
  value: categorical_crossentropy
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.0008224899743729448
optimizer:
  desc: null
  value: adadelta
patience:
  desc: null
  value: 11
random_seed:
  desc: null
  value: 35
staircase:
  desc: null
  value: 'false'
validation_split:
  desc: null
  value: 0.295642252626588
verbose:
  desc: null
  value: 2
