wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1672940820.008607
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 23
      - 37
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_1:
  desc: null
  value: relu
activation_3:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 16
conv1_filters:
  desc: null
  value: 11
conv1_kernelsize:
  desc: null
  value: 6
decay_rate:
  desc: null
  value: 0.7516134674235473
decay_steps:
  desc: null
  value: 392
dense1_size:
  desc: null
  value: 97
dropout:
  desc: null
  value: 0.17924610961896453
epoch:
  desc: null
  value: 10
initial_learning_rate:
  desc: null
  value: 6.034058353778589e-05
log_freq:
  desc: null
  value: 1
loss:
  desc: null
  value: mean_squared_error
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.001448541088221914
optimizer:
  desc: null
  value: sgd
patience:
  desc: null
  value: 5
staircase:
  desc: null
  value: 'true'
validation_split:
  desc: null
  value: 0.2221284168560637
verbose:
  desc: null
  value: 1
