wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 25
conv1_filters:
  value: 15
conv1_kernelsize:
  value: 6
conv2_filters:
  value: 16
conv2_kernelsize:
  value: 6
decay_rate:
  value: 0.6422291359681934
decay_steps:
  value: 505
dense1_size:
  value: 59
dropout:
  value: 0.909755370287076
epoch:
  value: 8
epochs:
  value: 14
initial_learning_rate:
  value: 1.979664335617545e-06
layer_1:
  value: 751
layer_2:
  value: 16
learning_rate:
  value: 0.0007884983658456072
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0006830246531215191
optimizer:
  value: sgd
patience:
  value: 3
random_seed:
  value: 34
staircase:
  value: 'true'
validation_split:
  value: 0.18496823306012805
verbose:
  value: 1
