wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 51
conv1_filters:
  value: 13
conv1_kernelsize:
  value: 4
conv2_filters:
  value: 29
conv2_kernelsize:
  value: 6
decay_rate:
  value: 0.2526977483101879
decay_steps:
  value: 187
dense1_size:
  value: 93
dropout:
  value: 0.3479733315763083
epoch:
  value: 7
epochs:
  value: 10
initial_learning_rate:
  value: 9.907912715744606e-07
layer_1:
  value: 335
layer_2:
  value: 18
learning_rate:
  value: 0.0006983322317157592
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0016958752165332747
optimizer:
  value: sgd
patience:
  value: 6
random_seed:
  value: 23
staircase:
  value: 'true'
validation_split:
  value: 0.3599053677110483
verbose:
  value: 2
