wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 18
conv1_filters:
  value: 13
conv1_kernelsize:
  value: 5
conv2_filters:
  value: 31
conv2_kernelsize:
  value: 5
decay_rate:
  value: 0.6820830550872107
decay_steps:
  value: 448
dense1_size:
  value: 104
dropout:
  value: 0.9598885108404072
epoch:
  value: 4
epochs:
  value: 5
initial_learning_rate:
  value: 1.253233061891317e-06
layer_1:
  value: 846
layer_2:
  value: 10
learning_rate:
  value: 0.0007717094993592425
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001499177672208299
optimizer:
  value: sgd
patience:
  value: 3
random_seed:
  value: 25
staircase:
  value: 'true'
validation_split:
  value: 0.22748114429390823
verbose:
  value: 1
