wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 56
conv1_filters:
  value: 9
conv1_kernelsize:
  value: 4
conv2_filters:
  value: 29
conv2_kernelsize:
  value: 4
decay_rate:
  value: 0.791277992909845
decay_steps:
  value: 218
dense1_size:
  value: 83
dropout:
  value: 0.8398247242090133
epoch:
  value: 15
epochs:
  value: 5
initial_learning_rate:
  value: 8.046430832549154e-07
layer_1:
  value: 546
layer_2:
  value: 11
learning_rate:
  value: 0.0013474915790529672
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0010709426374895803
optimizer:
  value: sgd
patience:
  value: 3
random_seed:
  value: 58
staircase:
  value: 'true'
validation_split:
  value: 0.39190978557238865
verbose:
  value: 1
