wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 22
conv1_filters:
  value: 8
conv1_kernelsize:
  value: 5
conv2_filters:
  value: 8
conv2_kernelsize:
  value: 6
decay_rate:
  value: 0.8914481067985056
decay_steps:
  value: 209
dense1_size:
  value: 87
dropout:
  value: 0.22134062041347252
epoch:
  value: 7
epochs:
  value: 7
initial_learning_rate:
  value: 1.5329319714672714e-06
layer_1:
  value: 500
layer_2:
  value: 14
learning_rate:
  value: 0.0015904333179281823
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0008279519003974853
optimizer:
  value: sgd
patience:
  value: 5
random_seed:
  value: 56
staircase:
  value: 'true'
validation_split:
  value: 0.3632125301684702
verbose:
  value: 2
