wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: tanh
batch_size:
  value: 74
decay_rate:
  value: 1.1641674737040917
decay_steps:
  value: 504
dense1_size:
  value: 152
dense2_size:
  value: 38
dropout:
  value: 0.2947627644520355
epoch:
  value: 25
initial_learning_rate:
  value: 0.0004634312805132884
log_freq:
  value: 1
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.00261037017369111
optimizer:
  value: sgd
patience:
  value: 4
staircase:
  value: 'false'
validation_split:
  value: 0.42202268467794835
verbose:
  value: 3
