wandb_version: 1

activation_3:
  value: tanh
activation_4:
  value: tanh
batch_size:
  value: 204
decay_rate:
  value: 0.978451501286468
decay_steps:
  value: 266
dense1_size:
  value: 125
dense2_size:
  value: 23
dropout:
  value: 0.3949533537139487
epoch:
  value: 8
initial_learning_rate:
  value: 0.0031107151132299107
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0039269860678209515
optimizer:
  value: sgd
patience:
  value: 6
staircase:
  value: 'true'
validation_split:
  value: 0.24164743888720255
verbose:
  value: 1
