wandb_version: 1

activation_3:
  value: sigmoid
activation_4:
  value: tanh
batch_size:
  value: 115
decay_rate:
  value: 1.690160939918732
decay_steps:
  value: 542
dense1_size:
  value: 130
dense2_size:
  value: 84
dropout:
  value: 0.263603941797948
epoch:
  value: 7
initial_learning_rate:
  value: 0.0026370743330504766
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0004649242972043085
optimizer:
  value: sgd
patience:
  value: 5
staircase:
  value: 'true'
validation_split:
  value: 0.5788578491686543
verbose:
  value: 2
