wandb_version: 1

activation_3:
  value: tanh
activation_4:
  value: relu
batch_size:
  value: 39
decay_rate:
  value: 0.4806035364379274
decay_steps:
  value: 217
dense1_size:
  value: 118
dense2_size:
  value: 78
dropout:
  value: 0.08796664156005926
epoch:
  value: 19
initial_learning_rate:
  value: 0.001397858296827786
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0026167532821567982
optimizer:
  value: sgd
patience:
  value: 3
staircase:
  value: 'false'
validation_split:
  value: 0.1759408910093322
verbose:
  value: 4
