wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: batch/batch_step
      6:
      - 3
    - 1: batch/loss
      5: 1
      6:
      - 1
    - 1: batch/accuracy
      5: 1
      6:
      - 1
    - 1: batch/learning_rate
      5: 1
      6:
      - 1
    python_version: 3.9.6
    start_time: 1672942252.820911
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 7
      - 23
      - 37
      - 38
      - 39
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_3:
  desc: null
  value: relu
activation_4:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 48
decay_rate:
  desc: null
  value: 0.9354470457596036
decay_steps:
  desc: null
  value: 389
dense1_size:
  desc: null
  value: 106
dense2_size:
  desc: null
  value: 16
dropout:
  desc: null
  value: 0.08724894088808788
epoch:
  desc: null
  value: 15
initial_learning_rate:
  desc: null
  value: 0.0018542022630834815
log_freq:
  desc: null
  value: 2
loss:
  desc: null
  value: mean_squared_error
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.0006034726351122577
optimizer:
  desc: null
  value: adamax
patience:
  desc: null
  value: 7
random_seed:
  desc: null
  value: 31
staircase:
  desc: null
  value: 'true'
validation_split:
  desc: null
  value: 0.3738950985030125
verbose:
  desc: null
  value: 1
