wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: batch/batch_step
      6:
      - 3
    - 1: batch/loss
      5: 1
      6:
      - 1
    - 1: batch/accuracy
      5: 1
      6:
      - 1
    - 1: batch/learning_rate
      5: 1
      6:
      - 1
    python_version: 3.9.6
    start_time: 1672944240.528751
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 7
      - 23
      - 37
      - 38
      - 39
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_3:
  desc: null
  value: tanh
activation_4:
  desc: null
  value: sigmoid
batch_size:
  desc: null
  value: 60
decay_rate:
  desc: null
  value: 1.111239072483431
decay_steps:
  desc: null
  value: 570
dense1_size:
  desc: null
  value: 140
dense2_size:
  desc: null
  value: 16
dropout:
  desc: null
  value: 0.36138869462733825
epoch:
  desc: null
  value: 11
initial_learning_rate:
  desc: null
  value: 9.54360546132022e-05
log_freq:
  desc: null
  value: 2
loss:
  desc: null
  value: categorical_crossentropy
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.001163662583472991
optimizer:
  desc: null
  value: adam
patience:
  desc: null
  value: 6
staircase:
  desc: null
  value: 'true'
validation_split:
  desc: null
  value: 0.2678688029551045
verbose:
  desc: null
  value: 3
