wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1672940446.827902
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 23
      - 37
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_1:
  desc: null
  value: relu
activation_2:
  desc: null
  value: relu
activation_3:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 55
conv1_filters:
  desc: null
  value: 14
conv1_kernelsize:
  desc: null
  value: 4
conv2_filters:
  desc: null
  value: 24
conv2_kernelsize:
  desc: null
  value: 4
decay_rate:
  desc: null
  value: 0.4860881425915547
decay_steps:
  desc: null
  value: 530
dense1_size:
  desc: null
  value: 82
dropout:
  desc: null
  value: 0.2876717493293388
epoch:
  desc: null
  value: 6
initial_learning_rate:
  desc: null
  value: 0.00017657013661625943
loss:
  desc: null
  value: mean_squared_error
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.0011620704472478267
optimizer:
  desc: null
  value: sgd
patience:
  desc: null
  value: 34
staircase:
  desc: null
  value: 'false'
validation_split:
  desc: null
  value: 0.14729429227992216
verbose:
  desc: null
  value: 2
