wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 51
conv1_filters:
  value: 15
conv1_kernelsize:
  value: 6
conv2_filters:
  value: 22
conv2_kernelsize:
  value: 5
decay_rate:
  value: 0.43860550603722503
decay_steps:
  value: 413
dense1_size:
  value: 82
dropout:
  value: 0.4008976445103484
epoch:
  value: 14
epochs:
  value: 10
initial_learning_rate:
  value: 1.8422897205403976e-06
layer_1:
  value: 273
layer_2:
  value: 13
learning_rate:
  value: 0.001990834919952444
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0010029703419331337
optimizer:
  value: sgd
patience:
  value: 7
random_seed:
  value: 82
staircase:
  value: 'true'
validation_split:
  value: 0.31074654649367617
verbose:
  value: 1
