wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 38
conv1_filters:
  value: 16
conv1_kernelsize:
  value: 3
conv2_filters:
  value: 28
conv2_kernelsize:
  value: 4
decay_rate:
  value: 0.779922397084654
decay_steps:
  value: 446
dense1_size:
  value: 34
dropout:
  value: 0.4563320079927753
epoch:
  value: 9
epochs:
  value: 9
initial_learning_rate:
  value: 1.6329534071993091e-06
layer_1:
  value: 611
layer_2:
  value: 10
learning_rate:
  value: 0.0009522210431677968
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0007094859633994024
optimizer:
  value: sgd
patience:
  value: 5
random_seed:
  value: 22
staircase:
  value: 'false'
validation_split:
  value: 0.22364180566159303
verbose:
  value: 1
