wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 23
conv1_filters:
  value: 15
conv1_kernelsize:
  value: 7
conv2_filters:
  value: 17
conv2_kernelsize:
  value: 2
decay_rate:
  value: 0.7120049552108458
decay_steps:
  value: 505
dense1_size:
  value: 67
dropout:
  value: 0.5966730736671041
epoch:
  value: 4
epochs:
  value: 18
initial_learning_rate:
  value: 1.90710537079249e-06
layer_1:
  value: 840
layer_2:
  value: 9
learning_rate:
  value: 0.0011408204814191852
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001975862479048863
optimizer:
  value: sgd
patience:
  value: 4
random_seed:
  value: 38
staircase:
  value: 'true'
validation_split:
  value: 0.3669216635989986
verbose:
  value: 2
