wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: batch/batch_step
      6:
      - 3
    - 1: batch/loss
      5: 1
      6:
      - 1
    - 1: batch/accuracy
      5: 1
      6:
      - 1
    - 1: batch/learning_rate
      5: 1
      6:
      - 1
    python_version: 3.9.6
    start_time: 1672952988.070855
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 7
      - 23
      - 37
      - 38
      - 39
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_3:
  desc: null
  value: sigmoid
activation_4:
  desc: null
  value: sigmoid
batch_size:
  desc: null
  value: 106
decay_rate:
  desc: null
  value: 1.34128723336041
decay_steps:
  desc: null
  value: 251
dense1_size:
  desc: null
  value: 128
dense2_size:
  desc: null
  value: 60
dropout:
  desc: null
  value: 0.3164089032171647
epoch:
  desc: null
  value: 15
initial_learning_rate:
  desc: null
  value: 0.0023472116406917367
log_freq:
  desc: null
  value: 2
loss:
  desc: null
  value: categorical_crossentropy
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.0033663384068399844
optimizer:
  desc: null
  value: sgd
patience:
  desc: null
  value: 14
random_seed:
  desc: null
  value: 82
staircase:
  desc: null
  value: 'true'
validation_split:
  desc: null
  value: 0.3677596676719376
verbose:
  desc: null
  value: 3
