wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: batch/batch_step
      6:
      - 3
    - 1: batch/loss
      5: 1
      6:
      - 1
    - 1: batch/accuracy
      5: 1
      6:
      - 1
    - 1: batch/learning_rate
      5: 1
      6:
      - 1
    python_version: 3.9.6
    start_time: 1672944919.539309
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 7
      - 23
      - 37
      - 38
      - 39
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_3:
  desc: null
  value: tanh
activation_4:
  desc: null
  value: sigmoid
batch_size:
  desc: null
  value: 46
decay_rate:
  desc: null
  value: 1.5368656442800055
decay_steps:
  desc: null
  value: 345
dense1_size:
  desc: null
  value: 139
dense2_size:
  desc: null
  value: 98
dropout:
  desc: null
  value: 0.14029886796996507
epoch:
  desc: null
  value: 26
initial_learning_rate:
  desc: null
  value: 6.755712503576025e-05
log_freq:
  desc: null
  value: 1
loss:
  desc: null
  value: mean_squared_error
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.0018833935449911567
optimizer:
  desc: null
  value: adamax
patience:
  desc: null
  value: 8
staircase:
  desc: null
  value: 'false'
validation_split:
  desc: null
  value: 0.18926286809338133
verbose:
  desc: null
  value: 3
