wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 101
dense1_size:
  value: 133
dense2_size:
  value: 76
dropout:
  value: 0.3912792564061651
epoch:
  value: 14
initial_learning_rate:
  value: 0.0035843945906284505
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.000887772532527264
validation_split:
  value: 0.2453009449589635
