wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 75
dense1_size:
  value: 152
dense2_size:
  value: 48
dropout:
  value: 0.08361606221326669
epoch:
  value: 5
initial_learning_rate:
  value: 0.001289736173254105
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0008227595031778197
validation_split:
  value: 0.5476961735253376
