wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 113
dense1_size:
  value: 33
dense2_size:
  value: 69
dropout:
  value: 0.3651345195143228
epoch:
  value: 18
initial_learning_rate:
  value: 0.0008090471589211229
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0023206470966728645
validation_split:
  value: 0.4929689018010528
