wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1672943458.162349
    t:
      1:
      - 2
      - 3
      - 55
      3:
      - 23
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_3:
  desc: null
  value: relu
activation_4:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 51
decay_rate:
  desc: null
  value: 0.7021165741014885
decay_steps:
  desc: null
  value: 271
dense1_size:
  desc: null
  value: 100
dense2_size:
  desc: null
  value: 22
dropout:
  desc: null
  value: 0.3760778985981621
epoch:
  desc: null
  value: 14
initial_learning_rate:
  desc: null
  value: 0.001760306825525442
log_freq:
  desc: null
  value: 2
loss:
  desc: null
  value: categorical_crossentropy
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.0016410834251289893
optimizer:
  desc: null
  value: adadelta
patience:
  desc: null
  value: 5
random_seed:
  desc: null
  value: 57
staircase:
  desc: null
  value: 'true'
validation_split:
  desc: null
  value: 0.10553435193168248
verbose:
  desc: null
  value: 2
