wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1672954402.19399
    t:
      1:
      - 2
      - 3
      - 55
      3:
      - 16
      - 23
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_3:
  desc: null
  value: sigmoid
activation_4:
  desc: null
  value: sigmoid
batch_size:
  desc: null
  value: 256
decay_rate:
  desc: null
  value: 0.95
decay_steps:
  desc: null
  value: 300
dense1_size:
  desc: null
  value: 128
dense2_size:
  desc: null
  value: 32
dropout:
  desc: null
  value: 0
epoch:
  desc: null
  value: 1000
initial_learning_rate:
  desc: null
  value: 1.0e-06
log_freq:
  desc: null
  value: 11
loss:
  desc: null
  value: mean_squared_error
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.001
optimizer:
  desc: null
  value: sgd
patience:
  desc: null
  value: 75
staircase:
  desc: null
  value: true
validation_split:
  desc: null
  value: 0.2
verbose:
  desc: null
  value: 1
