wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1672941589.105075
    t:
      1:
      - 2
      - 3
      - 55
      3:
      - 23
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_3:
  desc: null
  value: relu
activation_4:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 55
decay_rate:
  desc: null
  value: 0.692727234757489
decay_steps:
  desc: null
  value: 261
dense1_size:
  desc: null
  value: 95
dense2_size:
  desc: null
  value: 49
dropout:
  desc: null
  value: 0.323028052883345
epoch:
  desc: null
  value: 16
initial_learning_rate:
  desc: null
  value: 0.0002362512529954707
log_freq:
  desc: null
  value: 2
loss:
  desc: null
  value: categorical_crossentropy
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.0007152801617163073
optimizer:
  desc: null
  value: sgd
patience:
  desc: null
  value: 4
random_seed:
  desc: null
  value: 38
staircase:
  desc: null
  value: 'false'
validation_split:
  desc: null
  value: 0.1627751462415007
verbose:
  desc: null
  value: 1
