wandb_version: 1

activation_3:
  value: tanh
activation_4:
  value: sigmoid
batch_size:
  value: 77
conv1_filters:
  value: 5
conv1_kernelsize:
  value: 5
conv2_filters:
  value: 21
conv2_kernelsize:
  value: 5
decay_rate:
  value: 1.3432660347787568
decay_steps:
  value: 327
dense1_size:
  value: 152
dense2_size:
  value: 35
dropout:
  value: 0.1826600981958459
epoch:
  value: 20
initial_learning_rate:
  value: 0.001762522223066803
log_freq:
  value: 2
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0034823546829075005
optimizer:
  value: sgd
patience:
  value: 12
staircase:
  value: 'true'
validation_split:
  value: 0.5418781033997788
verbose:
  value: 2
