wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: tanh
batch_size:
  value: 40
conv1_filters:
  value: 16
conv1_kernelsize:
  value: 7
conv2_filters:
  value: 28
conv2_kernelsize:
  value: 2
decay_rate:
  value: 1.4819283621522463
decay_steps:
  value: 482
dense1_size:
  value: 86
dense2_size:
  value: 43
dropout:
  value: 0.19343081361021291
epoch:
  value: 27
initial_learning_rate:
  value: 0.0029556257944777977
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.002831554243989333
optimizer:
  value: adam
patience:
  value: 14
staircase:
  value: 'true'
validation_split:
  value: 0.3675113872988433
verbose:
  value: 2
