wandb_version: 1

activation_3:
  value: sigmoid
activation_4:
  value: relu
batch_size:
  value: 55
conv1_filters:
  value: 12
conv1_kernelsize:
  value: 10
conv2_filters:
  value: 16
conv2_kernelsize:
  value: 5
decay_rate:
  value: 0.3519949283612298
decay_steps:
  value: 445
dense1_size:
  value: 68
dense2_size:
  value: 79
dropout:
  value: 0.2126521209929533
epoch:
  value: 15
initial_learning_rate:
  value: 0.0024114949414563297
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.00221972407257126
optimizer:
  value: sgd
patience:
  value: 7
staircase:
  value: 'false'
validation_split:
  value: 0.09441241374909956
verbose:
  value: 3
