wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1672953961.754199
    t:
      1:
      - 2
      - 3
      - 55
      3:
      - 23
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_3:
  desc: null
  value: relu
activation_4:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 113
dense1_size:
  desc: null
  value: 33
dense2_size:
  desc: null
  value: 69
dropout:
  desc: null
  value: 0.3651345195143228
epoch:
  desc: null
  value: 18
initial_learning_rate:
  desc: null
  value: 0.0008090471589211229
loss:
  desc: null
  value: categorical_crossentropy
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.0023206470966728645
validation_split:
  desc: null
  value: 0.4929689018010528
