wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1672953935.59752
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 23
      - 37
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_3:
  desc: null
  value: relu
activation_4:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 75
dense1_size:
  desc: null
  value: 152
dense2_size:
  desc: null
  value: 48
dropout:
  desc: null
  value: 0.08361606221326669
epoch:
  desc: null
  value: 5
initial_learning_rate:
  desc: null
  value: 0.001289736173254105
loss:
  desc: null
  value: categorical_crossentropy
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.0008227595031778197
validation_split:
  desc: null
  value: 0.5476961735253376
