wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1672940530.692351
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 23
      - 37
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_1:
  desc: null
  value: relu
activation_2:
  desc: null
  value: relu
activation_3:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 43
conv1_filters:
  desc: null
  value: 7
conv1_kernelsize:
  desc: null
  value: 10
conv2_filters:
  desc: null
  value: 9
conv2_kernelsize:
  desc: null
  value: 3
decay_rate:
  desc: null
  value: 0.7084365627984961
decay_steps:
  desc: null
  value: 188
dense1_size:
  desc: null
  value: 66
dropout:
  desc: null
  value: 0.29911895263612004
epoch:
  desc: null
  value: 4
initial_learning_rate:
  desc: null
  value: 4.082516150500944e-05
loss:
  desc: null
  value: mean_squared_error
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.0018651938154140072
optimizer:
  desc: null
  value: sgd
patience:
  desc: null
  value: 10
staircase:
  desc: null
  value: 'false'
validation_split:
  desc: null
  value: 0.3954502018796461
verbose:
  desc: null
  value: 1
