wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1672899627.149793
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 23
      - 37
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_1:
  desc: null
  value: relu
activation_2:
  desc: null
  value: softmax
activation_3:
  desc: null
  value: relu
architecture:
  desc: null
  value: CNN
batch_size:
  desc: null
  value: 52
conv1_filters:
  desc: null
  value: 4
conv1_kernelsize:
  desc: null
  value: 4
conv2_filters:
  desc: null
  value: 31
conv2_kernelsize:
  desc: null
  value: 6
decay_rate:
  desc: null
  value: 0.9389995999109942
decay_steps:
  desc: null
  value: 419
dense1_size:
  desc: null
  value: 109
dropout:
  desc: null
  value: 0.2874473885179223
epoch:
  desc: null
  value: 5
epochs:
  desc: null
  value: 17
initial_learning_rate:
  desc: null
  value: 1.942696028627362e-06
layer_1:
  desc: null
  value: 275
layer_2:
  desc: null
  value: 13
learning_rate:
  desc: null
  value: 0.0010733278583780837
log_freq:
  desc: null
  value: 2
loss:
  desc: null
  value: mean_squared_error
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.001015401076120861
optimizer:
  desc: null
  value: sgd
patience:
  desc: null
  value: 5
random_seed:
  desc: null
  value: 45
staircase:
  desc: null
  value: 'false'
validation_split:
  desc: null
  value: 0.28613584980194284
verbose:
  desc: null
  value: 1
