wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: batch/batch_step
      6:
      - 3
    - 1: batch/loss
      5: 1
      6:
      - 1
    - 1: batch/accuracy
      5: 1
      6:
      - 1
    - 1: batch/learning_rate
      5: 1
      6:
      - 1
    python_version: 3.9.6
    start_time: 1672945106.816564
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 7
      - 23
      - 37
      - 38
      - 39
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_3:
  desc: null
  value: sigmoid
activation_4:
  desc: null
  value: sigmoid
batch_size:
  desc: null
  value: 66
decay_rate:
  desc: null
  value: 1.194598755014992
decay_steps:
  desc: null
  value: 560
dense1_size:
  desc: null
  value: 116
dense2_size:
  desc: null
  value: 29
dropout:
  desc: null
  value: 0.19019543051435428
epoch:
  desc: null
  value: 13
initial_learning_rate:
  desc: null
  value: 0.0020779287801564145
log_freq:
  desc: null
  value: 1
loss:
  desc: null
  value: categorical_crossentropy
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.0013455307504001506
optimizer:
  desc: null
  value: adamax
patience:
  desc: null
  value: 3
staircase:
  desc: null
  value: 'true'
validation_split:
  desc: null
  value: 0.4164793828839771
verbose:
  desc: null
  value: 2
