wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1672940488.61243
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 23
      - 37
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_1:
  desc: null
  value: relu
activation_2:
  desc: null
  value: relu
activation_3:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 35
conv1_filters:
  desc: null
  value: 4
conv1_kernelsize:
  desc: null
  value: 6
conv2_filters:
  desc: null
  value: 13
conv2_kernelsize:
  desc: null
  value: 6
decay_rate:
  desc: null
  value: 0.6852971858231952
decay_steps:
  desc: null
  value: 212
dense1_size:
  desc: null
  value: 70
dropout:
  desc: null
  value: 0.2285282153152773
epoch:
  desc: null
  value: 7
initial_learning_rate:
  desc: null
  value: 9.500128162212966e-05
loss:
  desc: null
  value: mean_squared_error
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.0017161227229534877
optimizer:
  desc: null
  value: sgd
patience:
  desc: null
  value: 13
staircase:
  desc: null
  value: 'true'
validation_split:
  desc: null
  value: 0.11938662134163858
verbose:
  desc: null
  value: 2
