wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: batch/batch_step
      6:
      - 3
    - 1: batch/loss
      5: 1
      6:
      - 1
    - 1: batch/accuracy
      5: 1
      6:
      - 1
    - 1: batch/learning_rate
      5: 1
      6:
      - 1
    python_version: 3.9.6
    start_time: 1672900706.12841
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 7
      - 23
      - 37
      - 38
      - 39
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_1:
  desc: null
  value: relu
activation_2:
  desc: null
  value: relu
activation_3:
  desc: null
  value: relu
architecture:
  desc: null
  value: CNN
batch_size:
  desc: null
  value: 37
conv1_filters:
  desc: null
  value: 13
conv1_kernelsize:
  desc: null
  value: 6
conv2_filters:
  desc: null
  value: 19
conv2_kernelsize:
  desc: null
  value: 4
decay_rate:
  desc: null
  value: 0.4273381824786862
decay_steps:
  desc: null
  value: 457
dense1_size:
  desc: null
  value: 46
dropout:
  desc: null
  value: 0.6008658177000514
epoch:
  desc: null
  value: 12
epochs:
  desc: null
  value: 16
initial_learning_rate:
  desc: null
  value: 1.994544744068502e-06
layer_1:
  desc: null
  value: 268
layer_2:
  desc: null
  value: 7
learning_rate:
  desc: null
  value: 0.0018831261710872433
log_freq:
  desc: null
  value: 2
loss:
  desc: null
  value: mean_squared_error
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.001525529560649792
optimizer:
  desc: null
  value: sgd
patience:
  desc: null
  value: 7
random_seed:
  desc: null
  value: 21
staircase:
  desc: null
  value: 'false'
validation_split:
  desc: null
  value: 0.2981165953550368
verbose:
  desc: null
  value: 1
