wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: batch/batch_step
      6:
      - 3
    - 1: batch/loss
      5: 1
      6:
      - 1
    - 1: batch/accuracy
      5: 1
      6:
      - 1
    - 1: batch/learning_rate
      5: 1
      6:
      - 1
    python_version: 3.9.6
    start_time: 1672941546.924008
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 7
      - 23
      - 37
      - 38
      - 39
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_3:
  desc: null
  value: relu
activation_4:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 18
decay_rate:
  desc: null
  value: 0.7666957436679342
decay_steps:
  desc: null
  value: 380
dense1_size:
  desc: null
  value: 45
dense2_size:
  desc: null
  value: 22
dropout:
  desc: null
  value: 0.1944716780924989
epoch:
  desc: null
  value: 13
initial_learning_rate:
  desc: null
  value: 0.000935240353601328
log_freq:
  desc: null
  value: 1
loss:
  desc: null
  value: mean_squared_error
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.0019183187763529605
optimizer:
  desc: null
  value: sgd
patience:
  desc: null
  value: 6
random_seed:
  desc: null
  value: 83
staircase:
  desc: null
  value: 'false'
validation_split:
  desc: null
  value: 0.25694349299850117
verbose:
  desc: null
  value: 1
