wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 44
conv1_filters:
  value: 13
conv1_kernelsize:
  value: 3
conv2_filters:
  value: 32
conv2_kernelsize:
  value: 6
decay_rate:
  value: 0.940983057102694
decay_steps:
  value: 157
dense1_size:
  value: 38
dropout:
  value: 0.606792767081798
epoch:
  value: 6
epochs:
  value: 18
initial_learning_rate:
  value: 1.4578798872464945e-06
layer_1:
  value: 863
layer_2:
  value: 17
learning_rate:
  value: 0.0009779934637765774
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0006903331781015821
optimizer:
  value: sgd
patience:
  value: 4
random_seed:
  value: 56
staircase:
  value: 'false'
validation_split:
  value: 0.28294073811421905
verbose:
  value: 1
