wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 54
conv1_filters:
  value: 13
conv1_kernelsize:
  value: 6
conv2_filters:
  value: 14
conv2_kernelsize:
  value: 2
decay_rate:
  value: 0.8729151125193627
decay_steps:
  value: 157
dense1_size:
  value: 97
dropout:
  value: 0.13861310439529656
epoch:
  value: 11
epochs:
  value: 6
initial_learning_rate:
  value: 1.7562273232518804e-06
layer_1:
  value: 589
layer_2:
  value: 20
learning_rate:
  value: 0.0012562877618195489
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0016196564878194167
optimizer:
  value: sgd
patience:
  value: 7
random_seed:
  value: 33
staircase:
  value: 'false'
validation_split:
  value: 0.34551020552747347
verbose:
  value: 2
