wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 22
conv1_filters:
  value: 8
conv1_kernelsize:
  value: 4
conv2_filters:
  value: 17
conv2_kernelsize:
  value: 5
decay_rate:
  value: 0.5040197596403421
decay_steps:
  value: 492
dense1_size:
  value: 57
dropout:
  value: 0.4417788454428612
epoch:
  value: 4
epochs:
  value: 7
initial_learning_rate:
  value: 1.4965228435146995e-06
layer_1:
  value: 287
layer_2:
  value: 11
learning_rate:
  value: 0.0005401160835001681
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0010817616252846792
optimizer:
  value: sgd
patience:
  value: 8
random_seed:
  value: 32
staircase:
  value: 'false'
validation_split:
  value: 0.23377215252036015
verbose:
  value: 1
