wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 18
conv1_filters:
  value: 10
conv1_kernelsize:
  value: 10
conv2_filters:
  value: 18
conv2_kernelsize:
  value: 3
decay_rate:
  value: 0.9799492956833674
decay_steps:
  value: 494
dense1_size:
  value: 125
dropout:
  value: 0.861279310327495
epoch:
  value: 8
epochs:
  value: 6
initial_learning_rate:
  value: 1.7015316736791463e-06
layer_1:
  value: 283
layer_2:
  value: 15
learning_rate:
  value: 0.0007621536255803213
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001700496591334276
optimizer:
  value: sgd
patience:
  value: 3
random_seed:
  value: 32
staircase:
  value: 'true'
validation_split:
  value: 0.3854220925196879
verbose:
  value: 2
