wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 16
conv1_filters:
  value: 7
conv1_kernelsize:
  value: 7
conv2_filters:
  value: 10
conv2_kernelsize:
  value: 3
decay_rate:
  value: 0.48667427889075193
decay_steps:
  value: 557
dense1_size:
  value: 116
dropout:
  value: 0.891642346745264
epoch:
  value: 11
epochs:
  value: 7
initial_learning_rate:
  value: 1.6098075363562498e-06
layer_1:
  value: 274
layer_2:
  value: 20
learning_rate:
  value: 0.0012647406184295648
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0016669475319389285
optimizer:
  value: sgd
patience:
  value: 4
random_seed:
  value: 28
staircase:
  value: 'true'
validation_split:
  value: 0.37715149795949343
verbose:
  value: 2
