wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 27
conv1_filters:
  value: 16
conv1_kernelsize:
  value: 3
conv2_filters:
  value: 14
conv2_kernelsize:
  value: 4
decay_rate:
  value: 0.7020752971253454
decay_steps:
  value: 213
dense1_size:
  value: 82
dropout:
  value: 0.541990319090166
epoch:
  value: 15
epochs:
  value: 8
initial_learning_rate:
  value: 1.5490456486883544e-06
layer_1:
  value: 375
layer_2:
  value: 8
learning_rate:
  value: 0.0016850167264657989
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001088035468757037
optimizer:
  value: sgd
patience:
  value: 6
random_seed:
  value: 77
staircase:
  value: 'true'
validation_split:
  value: 0.1227803762091384
verbose:
  value: 1
