wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 20
conv1_filters:
  value: 9
conv1_kernelsize:
  value: 7
conv2_filters:
  value: 22
conv2_kernelsize:
  value: 5
decay_rate:
  value: 0.7220410016099821
decay_steps:
  value: 263
dense1_size:
  value: 41
dropout:
  value: 0.31325505763421785
epoch:
  value: 5
epochs:
  value: 20
initial_learning_rate:
  value: 9.753422380088349e-07
layer_1:
  value: 400
layer_2:
  value: 12
learning_rate:
  value: 0.0005022532589356034
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.000681802726742011
optimizer:
  value: sgd
patience:
  value: 3
random_seed:
  value: 67
staircase:
  value: 'false'
validation_split:
  value: 0.3257430915942584
verbose:
  value: 2
