wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 55
conv1_filters:
  value: 5
conv1_kernelsize:
  value: 6
conv2_filters:
  value: 30
conv2_kernelsize:
  value: 3
decay_rate:
  value: 0.5587548209892026
decay_steps:
  value: 337
dense1_size:
  value: 128
dropout:
  value: 0.8702150987469823
epoch:
  value: 10
epochs:
  value: 10
initial_learning_rate:
  value: 5.431968563887071e-07
layer_1:
  value: 994
layer_2:
  value: 15
learning_rate:
  value: 0.000946284837445898
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001872480636468944
optimizer:
  value: sgd
patience:
  value: 7
random_seed:
  value: 67
staircase:
  value: 'false'
validation_split:
  value: 0.13829316445167592
verbose:
  value: 2
