wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 63
conv1_filters:
  value: 4
conv1_kernelsize:
  value: 6
conv2_filters:
  value: 11
conv2_kernelsize:
  value: 2
decay_rate:
  value: 0.987584696775253
decay_steps:
  value: 581
dense1_size:
  value: 54
dropout:
  value: 1.2856762838374884
epoch:
  value: 14
epochs:
  value: 8
initial_learning_rate:
  value: 1.6877763631721667e-06
layer_1:
  value: 438
layer_2:
  value: 10
learning_rate:
  value: 0.0011723839559886831
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0009998035231564297
optimizer:
  value: sgd
patience:
  value: 9
random_seed:
  value: 69
staircase:
  value: 'false'
validation_split:
  value: 0.10730380938968426
verbose:
  value: 2
