wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 30
conv1_filters:
  value: 4
conv1_kernelsize:
  value: 7
conv2_filters:
  value: 15
conv2_kernelsize:
  value: 5
decay_rate:
  value: 0.8112411900339407
decay_steps:
  value: 390
dense1_size:
  value: 124
dropout:
  value: 0.3941394262211676
epoch:
  value: 8
epochs:
  value: 19
initial_learning_rate:
  value: 1.990763243895567e-06
layer_1:
  value: 927
layer_2:
  value: 9
learning_rate:
  value: 0.001574758635253714
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0012951718399528986
optimizer:
  value: sgd
patience:
  value: 9
random_seed:
  value: 75
staircase:
  value: 'true'
validation_split:
  value: 0.3961442834119573
verbose:
  value: 2
