wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 37
conv1_filters:
  value: 13
conv1_kernelsize:
  value: 6
conv2_filters:
  value: 19
conv2_kernelsize:
  value: 4
decay_rate:
  value: 0.4273381824786862
decay_steps:
  value: 457
dense1_size:
  value: 46
dropout:
  value: 0.6008658177000514
epoch:
  value: 12
epochs:
  value: 16
initial_learning_rate:
  value: 1.994544744068502e-06
layer_1:
  value: 268
layer_2:
  value: 7
learning_rate:
  value: 0.0018831261710872433
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001525529560649792
optimizer:
  value: sgd
patience:
  value: 7
random_seed:
  value: 21
staircase:
  value: 'false'
validation_split:
  value: 0.2981165953550368
verbose:
  value: 1
