wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 48
conv1_filters:
  value: 15
conv1_kernelsize:
  value: 10
conv2_filters:
  value: 8
conv2_kernelsize:
  value: 3
decay_rate:
  value: 0.8393536686675067
decay_steps:
  value: 308
dense1_size:
  value: 94
dropout:
  value: 0.3891925493951305
epoch:
  value: 5
epochs:
  value: 8
initial_learning_rate:
  value: 1.921697194760636e-06
layer_1:
  value: 659
layer_2:
  value: 20
learning_rate:
  value: 0.0017635607043454669
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0007071000433109111
optimizer:
  value: sgd
patience:
  value: 8
random_seed:
  value: 75
staircase:
  value: 'false'
validation_split:
  value: 0.23333052148539207
verbose:
  value: 2
