wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 56
conv1_filters:
  value: 7
conv1_kernelsize:
  value: 7
conv2_filters:
  value: 18
conv2_kernelsize:
  value: 5
decay_rate:
  value: 0.7287872299340881
decay_steps:
  value: 579
dense1_size:
  value: 114
dropout:
  value: 0.6461501675271885
epoch:
  value: 13
epochs:
  value: 7
initial_learning_rate:
  value: 1.9341767359332012e-06
layer_1:
  value: 882
layer_2:
  value: 14
learning_rate:
  value: 0.0009036516769878938
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001214220190976079
optimizer:
  value: sgd
patience:
  value: 10
random_seed:
  value: 74
staircase:
  value: 'false'
validation_split:
  value: 0.28112106606209264
verbose:
  value: 1
