wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 52
conv1_filters:
  value: 4
conv1_kernelsize:
  value: 4
conv2_filters:
  value: 31
conv2_kernelsize:
  value: 6
decay_rate:
  value: 0.9389995999109942
decay_steps:
  value: 419
dense1_size:
  value: 109
dropout:
  value: 0.2874473885179223
epoch:
  value: 5
epochs:
  value: 17
initial_learning_rate:
  value: 1.942696028627362e-06
layer_1:
  value: 275
layer_2:
  value: 13
learning_rate:
  value: 0.0010733278583780837
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001015401076120861
optimizer:
  value: sgd
patience:
  value: 5
random_seed:
  value: 45
staircase:
  value: 'false'
validation_split:
  value: 0.28613584980194284
verbose:
  value: 1
