wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 25
conv1_filters:
  value: 6
conv1_kernelsize:
  value: 6
conv2_filters:
  value: 29
conv2_kernelsize:
  value: 4
decay_rate:
  value: 0.32803353136874336
decay_steps:
  value: 503
dense1_size:
  value: 38
dropout:
  value: 1.380794955113663
epoch:
  value: 6
epochs:
  value: 20
initial_learning_rate:
  value: 1.7628671748983054e-06
layer_1:
  value: 623
layer_2:
  value: 17
learning_rate:
  value: 0.001504332838408676
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0007531893728730315
optimizer:
  value: sgd
patience:
  value: 10
random_seed:
  value: 47
staircase:
  value: 'false'
validation_split:
  value: 0.3888464258889378
verbose:
  value: 2
