wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 42
conv1_filters:
  value: 14
conv1_kernelsize:
  value: 6
conv2_filters:
  value: 27
conv2_kernelsize:
  value: 4
decay_rate:
  value: 0.4890148967081709
decay_steps:
  value: 361
dense1_size:
  value: 86
dropout:
  value: 0.9166103314730112
epoch:
  value: 15
epochs:
  value: 10
initial_learning_rate:
  value: 1.7425930219200053e-06
layer_1:
  value: 391
layer_2:
  value: 5
learning_rate:
  value: 0.0014778469960926954
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0011061012308924048
optimizer:
  value: sgd
patience:
  value: 9
random_seed:
  value: 42
staircase:
  value: 'false'
validation_split:
  value: 0.1541755135758962
verbose:
  value: 1
