wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 17
conv1_filters:
  value: 14
conv1_kernelsize:
  value: 3
conv2_filters:
  value: 8
conv2_kernelsize:
  value: 3
decay_rate:
  value: 0.4182550602619897
decay_steps:
  value: 336
dense1_size:
  value: 44
dropout:
  value: 0.626798564793303
epoch:
  value: 7
epochs:
  value: 12
initial_learning_rate:
  value: 9.855869081364226e-07
layer_1:
  value: 424
layer_2:
  value: 19
learning_rate:
  value: 0.00086185562738176
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0006625711290105594
optimizer:
  value: sgd
patience:
  value: 3
random_seed:
  value: 72
staircase:
  value: 'true'
validation_split:
  value: 0.2656038233445409
verbose:
  value: 1
