wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1672940467.255328
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 23
      - 37
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_1:
  desc: null
  value: relu
activation_2:
  desc: null
  value: relu
activation_3:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 17
conv1_filters:
  desc: null
  value: 5
conv1_kernelsize:
  desc: null
  value: 6
conv2_filters:
  desc: null
  value: 24
conv2_kernelsize:
  desc: null
  value: 6
decay_rate:
  desc: null
  value: 0.8009779432191604
decay_steps:
  desc: null
  value: 586
dense1_size:
  desc: null
  value: 35
dropout:
  desc: null
  value: 0.39781479181467183
epoch:
  desc: null
  value: 10
initial_learning_rate:
  desc: null
  value: 2.0096212542926932e-05
loss:
  desc: null
  value: mean_squared_error
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.0011011934989791049
optimizer:
  desc: null
  value: sgd
patience:
  desc: null
  value: 20
staircase:
  desc: null
  value: 'true'
validation_split:
  desc: null
  value: 0.27125582116071856
verbose:
  desc: null
  value: 2
