wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: batch/batch_step
      6:
      - 3
    - 1: batch/loss
      5: 1
      6:
      - 1
    - 1: batch/accuracy
      5: 1
      6:
      - 1
    - 1: batch/learning_rate
      5: 1
      6:
      - 1
    python_version: 3.9.6
    start_time: 1672942783.618517
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 7
      - 23
      - 37
      - 38
      - 39
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_3:
  desc: null
  value: relu
activation_4:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 32
decay_rate:
  desc: null
  value: 0.37862663477255715
decay_steps:
  desc: null
  value: 168
dense1_size:
  desc: null
  value: 61
dense2_size:
  desc: null
  value: 46
dropout:
  desc: null
  value: 0.09010618132731411
epoch:
  desc: null
  value: 13
initial_learning_rate:
  desc: null
  value: 0.00015384358617458988
log_freq:
  desc: null
  value: 1
loss:
  desc: null
  value: categorical_crossentropy
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.0014081837644113835
optimizer:
  desc: null
  value: adamax
patience:
  desc: null
  value: 4
random_seed:
  desc: null
  value: 69
staircase:
  desc: null
  value: 'true'
validation_split:
  desc: null
  value: 0.3345378969432402
verbose:
  desc: null
  value: 1
