wandb_version: 1

activation_1:
  value: relu
activation_3:
  value: relu
batch_size:
  value: 22
conv1_filters:
  value: 9
conv1_kernelsize:
  value: 6
decay_rate:
  value: 0.9674303609183168
decay_steps:
  value: 453
dense1_size:
  value: 100
dropout:
  value: 0.2297970481921528
epoch:
  value: 4
initial_learning_rate:
  value: 0.0011885283684122388
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0016743212346285907
optimizer:
  value: sgd
patience:
  value: 6
staircase:
  value: 'true'
validation_split:
  value: 0.2621276820921824
verbose:
  value: 1
