wandb_version: 1

activation_1:
  value: relu
activation_3:
  value: relu
batch_size:
  value: 33
conv1_filters:
  value: 14
conv1_kernelsize:
  value: 10
decay_rate:
  value: 0.6886668510436981
decay_steps:
  value: 212
dense1_size:
  value: 101
dropout:
  value: 0.380500979526346
epoch:
  value: 10
initial_learning_rate:
  value: 0.0010076398957974888
log_freq:
  value: 1
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0011022641703102222
optimizer:
  value: sgd
patience:
  value: 6
staircase:
  value: 'false'
validation_split:
  value: 0.3750822055534858
verbose:
  value: 2
