wandb_version: 1

activation_1:
  value: relu
activation_3:
  value: relu
batch_size:
  value: 16
conv1_filters:
  value: 11
conv1_kernelsize:
  value: 6
decay_rate:
  value: 0.7516134674235473
decay_steps:
  value: 392
dense1_size:
  value: 97
dropout:
  value: 0.17924610961896453
epoch:
  value: 10
initial_learning_rate:
  value: 6.034058353778589e-05
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001448541088221914
optimizer:
  value: sgd
patience:
  value: 5
staircase:
  value: 'true'
validation_split:
  value: 0.2221284168560637
verbose:
  value: 1
