wandb_version: 1

activation_1:
  value: relu
activation_3:
  value: relu
batch_size:
  value: 56
conv1_filters:
  value: 9
conv1_kernelsize:
  value: 9
decay_rate:
  value: 0.6921074416714349
decay_steps:
  value: 222
dense1_size:
  value: 70
dropout:
  value: 0.36198177295897704
epoch:
  value: 11
initial_learning_rate:
  value: 0.001105575298178182
log_freq:
  value: 1
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.000914671451850641
optimizer:
  value: sgd
patience:
  value: 7
staircase:
  value: 'true'
validation_split:
  value: 0.10109448308239816
verbose:
  value: 1
