wandb_version: 1

activation_3:
  value: tanh
activation_4:
  value: sigmoid
batch_size:
  value: 46
decay_rate:
  value: 1.5368656442800055
decay_steps:
  value: 345
dense1_size:
  value: 139
dense2_size:
  value: 98
dropout:
  value: 0.14029886796996507
epoch:
  value: 26
initial_learning_rate:
  value: 6.755712503576025e-05
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0018833935449911567
optimizer:
  value: adamax
patience:
  value: 8
staircase:
  value: 'false'
validation_split:
  value: 0.18926286809338133
verbose:
  value: 3
