wandb_version: 1

activation_3:
  value: tanh
activation_4:
  value: tanh
batch_size:
  value: 60
decay_rate:
  value: 0.9579414262435384
decay_steps:
  value: 237
dense1_size:
  value: 95
dense2_size:
  value: 109
dropout:
  value: 0.3160953592361096
epoch:
  value: 5
initial_learning_rate:
  value: 0.003101894981300259
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.003814035841009319
optimizer:
  value: adamax
patience:
  value: 5
staircase:
  value: 'true'
validation_split:
  value: 0.17956535146392394
verbose:
  value: 2
