wandb_version: 1

activation_3:
  value: tanh
activation_4:
  value: tanh
batch_size:
  value: 77
decay_rate:
  value: 0.9027569213937904
decay_steps:
  value: 166
dense1_size:
  value: 75
dense2_size:
  value: 54
dropout:
  value: 0.3275166433787709
epoch:
  value: 8
initial_learning_rate:
  value: 0.002402212481709782
log_freq:
  value: 1
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0016349600181040423
optimizer:
  value: adam
patience:
  value: 8
staircase:
  value: 'false'
validation_split:
  value: 0.20502997813083967
verbose:
  value: 2
