wandb_version: 1

activation_3:
  value: tanh
activation_4:
  value: tanh
batch_size:
  value: 103
decay_rate:
  value: 0.5674164705244398
decay_steps:
  value: 348
dense1_size:
  value: 135
dense2_size:
  value: 73
dropout:
  value: 0.22309918311405288
epoch:
  value: 12
initial_learning_rate:
  value: 0.0033102565524964255
log_freq:
  value: 1
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0009709906806944652
optimizer:
  value: adamax
patience:
  value: 12
staircase:
  value: 'true'
validation_split:
  value: 0.08668896519594772
verbose:
  value: 2
