wandb_version: 1

activation_3:
  value: tanh
activation_4:
  value: sigmoid
batch_size:
  value: 67
decay_rate:
  value: 1.5649897402538888
decay_steps:
  value: 558
dense1_size:
  value: 83
dense2_size:
  value: 78
dropout:
  value: 0.26304122807303315
epoch:
  value: 17
initial_learning_rate:
  value: 0.003176997681657924
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0031989950477590663
optimizer:
  value: adam
patience:
  value: 6
staircase:
  value: 'false'
validation_split:
  value: 0.3116857138503993
verbose:
  value: 4
