wandb_version: 1

activation_3:
  value: tanh
activation_4:
  value: sigmoid
batch_size:
  value: 100
decay_rate:
  value: 1.6542372579137
decay_steps:
  value: 263
dense1_size:
  value: 62
dense2_size:
  value: 84
dropout:
  value: 0.29435046904736595
epoch:
  value: 9
initial_learning_rate:
  value: 0.003174284480084757
log_freq:
  value: 2
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.001906632170748744
optimizer:
  value: adamax
patience:
  value: 5
staircase:
  value: 'false'
validation_split:
  value: 0.6761695572335845
verbose:
  value: 4
