wandb_version: 1

activation_3:
  value: sigmoid
activation_4:
  value: tanh
batch_size:
  value: 100
decay_rate:
  value: 0.7152295054655767
decay_steps:
  value: 131
dense1_size:
  value: 36
dense2_size:
  value: 56
dropout:
  value: 0.11434152981288824
epoch:
  value: 22
initial_learning_rate:
  value: 0.0008659073868544987
log_freq:
  value: 1
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.00168338622510292
optimizer:
  value: adamax
patience:
  value: 2
staircase:
  value: 'true'
validation_split:
  value: 0.561350522271626
verbose:
  value: 1
