wandb_version: 1

activation_3:
  value: tanh
activation_4:
  value: sigmoid
batch_size:
  value: 64
decay_rate:
  value: 1.1364278135606658
decay_steps:
  value: 483
dense1_size:
  value: 46
dense2_size:
  value: 89
dropout:
  value: 0.3270302051170931
epoch:
  value: 10
initial_learning_rate:
  value: 0.0001903182087786655
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0034222183624861837
optimizer:
  value: sgd
patience:
  value: 2
staircase:
  value: 'true'
validation_split:
  value: 0.532247765589468
verbose:
  value: 4
