wandb_version: 1

activation_3:
  value: sigmoid
activation_4:
  value: sigmoid
batch_size:
  value: 44
decay_rate:
  value: 1.4372376318488782
decay_steps:
  value: 255
dense1_size:
  value: 84
dense2_size:
  value: 18
dropout:
  value: 0.29165933761738644
epoch:
  value: 20
initial_learning_rate:
  value: 0.0038076570620107497
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0012380075776428751
optimizer:
  value: sgd
patience:
  value: 12
staircase:
  value: 'true'
validation_split:
  value: 0.3432722602562215
verbose:
  value: 3
