wandb_version: 1

activation_3:
  value: sigmoid
activation_4:
  value: sigmoid
batch_size:
  value: 66
decay_rate:
  value: 1.194598755014992
decay_steps:
  value: 560
dense1_size:
  value: 116
dense2_size:
  value: 29
dropout:
  value: 0.19019543051435428
epoch:
  value: 13
initial_learning_rate:
  value: 0.0020779287801564145
log_freq:
  value: 1
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0013455307504001506
optimizer:
  value: adamax
patience:
  value: 3
staircase:
  value: 'true'
validation_split:
  value: 0.4164793828839771
verbose:
  value: 2
