wandb_version: 1

activation_3:
  value: tanh
activation_4:
  value: tanh
batch_size:
  value: 122
decay_rate:
  value: 1.5755711320969508
decay_steps:
  value: 432
dense1_size:
  value: 149
dense2_size:
  value: 66
dropout:
  value: 0.1560826162121402
epoch:
  value: 26
initial_learning_rate:
  value: 0.003613783268705557
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.00183874402962349
optimizer:
  value: sgd
patience:
  value: 6
staircase:
  value: 'true'
validation_split:
  value: 0.1423119838493505
verbose:
  value: 3
