wandb_version: 1

activation_3:
  value: tanh
activation_4:
  value: tanh
batch_size:
  value: 109
decay_rate:
  value: 0.6666397346128483
decay_steps:
  value: 84
dense1_size:
  value: 59
dense2_size:
  value: 37
dropout:
  value: 0.3802453183851719
epoch:
  value: 4
initial_learning_rate:
  value: 0.0011641041551011
log_freq:
  value: 1
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0034711345017936724
optimizer:
  value: adam
patience:
  value: 13
staircase:
  value: 'false'
validation_split:
  value: 0.099988069212549
verbose:
  value: 4
