wandb_version: 1

activation_3:
  value: tanh
activation_4:
  value: tanh
batch_size:
  value: 62
decay_rate:
  value: 0.9288869626357366
decay_steps:
  value: 309
dense1_size:
  value: 49
dense2_size:
  value: 20
dropout:
  value: 0.3888066568782048
epoch:
  value: 26
initial_learning_rate:
  value: 0.002733036251338296
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0006019439290357562
optimizer:
  value: sgd
patience:
  value: 7
staircase:
  value: 'false'
validation_split:
  value: 0.5518063934211908
verbose:
  value: 4
