wandb_version: 1

activation_3:
  value: sigmoid
activation_4:
  value: sigmoid
batch_size:
  value: 51
decay_rate:
  value: 0.6628634208456794
decay_steps:
  value: 118
dense1_size:
  value: 100
dense2_size:
  value: 102
dropout:
  value: 0.3815883531415578
epoch:
  value: 8
initial_learning_rate:
  value: 0.0003199760940828106
log_freq:
  value: 2
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.001401807047943924
optimizer:
  value: adam
patience:
  value: 4
staircase:
  value: 'false'
validation_split:
  value: 0.6684556526899768
verbose:
  value: 4
