wandb_version: 1

activation_3:
  value: tanh
activation_4:
  value: tanh
batch_size:
  value: 81
decay_rate:
  value: 0.3310089550589534
decay_steps:
  value: 206
dense1_size:
  value: 74
dense2_size:
  value: 45
dropout:
  value: 0.3357040909376151
epoch:
  value: 14
initial_learning_rate:
  value: 0.002722343300645847
log_freq:
  value: 1
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.001146175665242075
optimizer:
  value: sgd
patience:
  value: 3
staircase:
  value: 'false'
validation_split:
  value: 0.5179587783538979
verbose:
  value: 4
