wandb_version: 1

activation_3:
  value: tanh
activation_4:
  value: sigmoid
batch_size:
  value: 60
decay_rate:
  value: 1.111239072483431
decay_steps:
  value: 570
dense1_size:
  value: 140
dense2_size:
  value: 16
dropout:
  value: 0.36138869462733825
epoch:
  value: 11
initial_learning_rate:
  value: 9.54360546132022e-05
log_freq:
  value: 2
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.001163662583472991
optimizer:
  value: adam
patience:
  value: 6
staircase:
  value: 'true'
validation_split:
  value: 0.2678688029551045
verbose:
  value: 3
