wandb_version: 1

activation_3:
  value: tanh
activation_4:
  value: sigmoid
batch_size:
  value: 100
decay_rate:
  value: 0.5489505547338271
decay_steps:
  value: 559
dense1_size:
  value: 93
dense2_size:
  value: 72
dropout:
  value: 0.1152646680902163
epoch:
  value: 22
initial_learning_rate:
  value: 0.0009292001427896792
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.002731804383572449
optimizer:
  value: adamax
patience:
  value: 11
staircase:
  value: 'true'
validation_split:
  value: 0.08591185644853962
verbose:
  value: 3
