wandb_version: 1

activation_3:
  value: tanh
activation_4:
  value: tanh
batch_size:
  value: 27
decay_rate:
  value: 1.039337929282255
decay_steps:
  value: 112
dense1_size:
  value: 101
dense2_size:
  value: 96
dropout:
  value: 0.08546562458342179
epoch:
  value: 27
initial_learning_rate:
  value: 0.002782580992800194
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.003824700961109692
optimizer:
  value: sgd
patience:
  value: 7
staircase:
  value: 'false'
validation_split:
  value: 0.29761863876468475
verbose:
  value: 4
