wandb_version: 1

activation_3:
  value: sigmoid
activation_4:
  value: sigmoid
batch_size:
  value: 109
decay_rate:
  value: 0.7531542740795637
decay_steps:
  value: 418
dense1_size:
  value: 113
dense2_size:
  value: 34
dropout:
  value: 0.10830663320629924
epoch:
  value: 10
initial_learning_rate:
  value: 0.0012744833716910194
log_freq:
  value: 1
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0009425128712570016
optimizer:
  value: sgd
patience:
  value: 12
staircase:
  value: 'true'
validation_split:
  value: 0.22473868656854856
verbose:
  value: 1
