wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: batch/batch_step
      6:
      - 3
    - 1: batch/loss
      5: 1
      6:
      - 1
    - 1: batch/accuracy
      5: 1
      6:
      - 1
    - 1: batch/learning_rate
      5: 1
      6:
      - 1
    python_version: 3.9.6
    start_time: 1672944640.607307
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 7
      - 23
      - 37
      - 38
      - 39
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_3:
  desc: null
  value: tanh
activation_4:
  desc: null
  value: tanh
batch_size:
  desc: null
  value: 60
decay_rate:
  desc: null
  value: 0.9579414262435384
decay_steps:
  desc: null
  value: 237
dense1_size:
  desc: null
  value: 95
dense2_size:
  desc: null
  value: 109
dropout:
  desc: null
  value: 0.3160953592361096
epoch:
  desc: null
  value: 5
initial_learning_rate:
  desc: null
  value: 0.003101894981300259
log_freq:
  desc: null
  value: 2
loss:
  desc: null
  value: mean_squared_error
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.003814035841009319
optimizer:
  desc: null
  value: adamax
patience:
  desc: null
  value: 5
staircase:
  desc: null
  value: 'true'
validation_split:
  desc: null
  value: 0.17956535146392394
verbose:
  desc: null
  value: 2
