wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: sigmoid
batch_size:
  value: 411
dense1_size:
  value: 121
dense2_size:
  value: 54
dropout:
  value: 0.3518461110409318
epoch:
  value: 6
initial_learning_rate:
  value: 0.0030153279171314298
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0012091814790077095
