wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: sigmoid
batch_size:
  value: 374
dense1_size:
  value: 98
dense2_size:
  value: 89
dropout:
  value: 0.054937219309792375
epoch:
  value: 6
initial_learning_rate:
  value: 0.002440482874760439
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.003135780783933997
