wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1672952458.164671
    t:
      1:
      - 2
      - 3
      - 55
      3:
      - 23
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_3:
  desc: null
  value: sigmoid
activation_4:
  desc: null
  value: sigmoid
batch_size:
  desc: null
  value: 30
decay_rate:
  desc: null
  value: 0.6498839256388214
decay_steps:
  desc: null
  value: 600
dense1_size:
  desc: null
  value: 52
dense2_size:
  desc: null
  value: 97
dropout:
  desc: null
  value: 0.37477504064785494
epoch:
  desc: null
  value: 25
initial_learning_rate:
  desc: null
  value: 0.002911453490209871
log_freq:
  desc: null
  value: 2
loss:
  desc: null
  value: categorical_crossentropy
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.003405695683090428
optimizer:
  desc: null
  value: sgd
patience:
  desc: null
  value: 9
staircase:
  desc: null
  value: 'false'
validation_split:
  desc: null
  value: 0.17193688045926006
verbose:
  desc: null
  value: 4
