wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 18
decay_rate:
  value: 0.7666957436679342
decay_steps:
  value: 380
dense1_size:
  value: 45
dense2_size:
  value: 22
dropout:
  value: 0.1944716780924989
epoch:
  value: 13
initial_learning_rate:
  value: 0.000935240353601328
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0019183187763529605
optimizer:
  value: sgd
patience:
  value: 6
random_seed:
  value: 83
staircase:
  value: 'false'
validation_split:
  value: 0.25694349299850117
verbose:
  value: 1
