wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 64
decay_rate:
  value: 0.3854932095444149
decay_steps:
  value: 590
dense1_size:
  value: 64
dense2_size:
  value: 50
dropout:
  value: 0.2973465873392988
epoch:
  value: 8
initial_learning_rate:
  value: 0.0005643279468139162
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0008779027787196636
optimizer:
  value: sgd
patience:
  value: 6
random_seed:
  value: 74
staircase:
  value: 'false'
validation_split:
  value: 0.24566704874102752
verbose:
  value: 2
