wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 27
decay_rate:
  value: 0.5835732427407168
decay_steps:
  value: 484
dense1_size:
  value: 117
dense2_size:
  value: 59
dropout:
  value: 0.3759211882457486
epoch:
  value: 16
initial_learning_rate:
  value: 0.0015855237995808318
log_freq:
  value: 2
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0012824763211970866
optimizer:
  value: sgd
patience:
  value: 8
random_seed:
  value: 65
staircase:
  value: 'true'
validation_split:
  value: 0.2769009759266865
verbose:
  value: 1
