wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1672944001.212917
    t:
      1:
      - 2
      - 3
      - 55
      3:
      - 23
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_3:
  desc: null
  value: relu
activation_4:
  desc: null
  value: tanh
batch_size:
  desc: null
  value: 185
decay_rate:
  desc: null
  value: 1.4164972298278538
decay_steps:
  desc: null
  value: 420
dense1_size:
  desc: null
  value: 141
dense2_size:
  desc: null
  value: 76
dropout:
  desc: null
  value: 0.34969772917950986
epoch:
  desc: null
  value: 9
initial_learning_rate:
  desc: null
  value: 0.0035019945505313406
log_freq:
  desc: null
  value: 2
loss:
  desc: null
  value: categorical_crossentropy
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.003647793151527112
optimizer:
  desc: null
  value: sgd
patience:
  desc: null
  value: 6
staircase:
  desc: null
  value: 'false'
validation_split:
  desc: null
  value: 0.2994257912247954
verbose:
  desc: null
  value: 1
