wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1672899920.669595
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 23
      - 37
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_1:
  desc: null
  value: relu
activation_2:
  desc: null
  value: softmax
activation_3:
  desc: null
  value: relu
architecture:
  desc: null
  value: CNN
batch_size:
  desc: null
  value: 38
conv1_filters:
  desc: null
  value: 16
conv1_kernelsize:
  desc: null
  value: 3
conv2_filters:
  desc: null
  value: 28
conv2_kernelsize:
  desc: null
  value: 4
decay_rate:
  desc: null
  value: 0.779922397084654
decay_steps:
  desc: null
  value: 446
dense1_size:
  desc: null
  value: 34
dropout:
  desc: null
  value: 0.4563320079927753
epoch:
  desc: null
  value: 9
epochs:
  desc: null
  value: 9
initial_learning_rate:
  desc: null
  value: 1.6329534071993091e-06
layer_1:
  desc: null
  value: 611
layer_2:
  desc: null
  value: 10
learning_rate:
  desc: null
  value: 0.0009522210431677968
log_freq:
  desc: null
  value: 2
loss:
  desc: null
  value: mean_squared_error
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.0007094859633994024
optimizer:
  desc: null
  value: sgd
patience:
  desc: null
  value: 5
random_seed:
  desc: null
  value: 22
staircase:
  desc: null
  value: 'false'
validation_split:
  desc: null
  value: 0.22364180566159303
verbose:
  desc: null
  value: 1
