wandb_version: 1

activation_3:
  value: sigmoid
activation_4:
  value: sigmoid
batch_size:
  value: 61
decay_rate:
  value: 1.050925994557622
decay_steps:
  value: 536
dense1_size:
  value: 39
dense2_size:
  value: 100
dropout:
  value: 0.29261589801830334
epoch:
  value: 6
initial_learning_rate:
  value: 0.0018322142648554297
log_freq:
  value: 1
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0013686615870942304
optimizer:
  value: sgd
patience:
  value: 6
random_seed:
  value: 129
staircase:
  value: 'false'
validation_split:
  value: 0.4638162118563953
verbose:
  value: 2
