wandb_version: 1

activation_3:
  value: sigmoid
activation_4:
  value: sigmoid
batch_size:
  value: 93
decay_rate:
  value: 0.7879755183470627
decay_steps:
  value: 506
dense1_size:
  value: 64
dense2_size:
  value: 86
dropout:
  value: 0.2715643898119579
epoch:
  value: 27
initial_learning_rate:
  value: 0.0009639648356176228
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0024701562157699005
optimizer:
  value: sgd
patience:
  value: 9
random_seed:
  value: 98
staircase:
  value: 'true'
validation_split:
  value: 0.10264404923153508
verbose:
  value: 2
