wandb_version: 1

activation_3:
  value: sigmoid
activation_4:
  value: sigmoid
batch_size:
  value: 106
decay_rate:
  value: 1.34128723336041
decay_steps:
  value: 251
dense1_size:
  value: 128
dense2_size:
  value: 60
dropout:
  value: 0.3164089032171647
epoch:
  value: 15
initial_learning_rate:
  value: 0.0023472116406917367
log_freq:
  value: 2
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0033663384068399844
optimizer:
  value: sgd
patience:
  value: 14
random_seed:
  value: 82
staircase:
  value: 'true'
validation_split:
  value: 0.3677596676719376
verbose:
  value: 3
