wandb_version: 1

activation_3:
  value: sigmoid
activation_4:
  value: sigmoid
batch_size:
  value: 38
decay_rate:
  value: 1.3382383844485712
decay_steps:
  value: 220
dense1_size:
  value: 150
dense2_size:
  value: 54
dropout:
  value: 0.3724079136969704
epoch:
  value: 14
initial_learning_rate:
  value: 0.002251656166407609
log_freq:
  value: 2
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0008429575521818138
optimizer:
  value: sgd
patience:
  value: 14
random_seed:
  value: 30
staircase:
  value: 'false'
validation_split:
  value: 0.5791774783932438
verbose:
  value: 3
