wandb_version: 1

activation_3:
  value: sigmoid
activation_4:
  value: sigmoid
batch_size:
  value: 89
decay_rate:
  value: 0.35324548950715995
decay_steps:
  value: 155
dense1_size:
  value: 148
dense2_size:
  value: 29
dropout:
  value: 0.28113703753124697
epoch:
  value: 9
initial_learning_rate:
  value: 8.763747141381943e-06
log_freq:
  value: 1
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0004140541891157461
optimizer:
  value: sgd
patience:
  value: 6
random_seed:
  value: 86
staircase:
  value: 'true'
validation_split:
  value: 0.5530641100967614
verbose:
  value: 2
