wandb_version: 1

activation_3:
  value: sigmoid
activation_4:
  value: sigmoid
batch_size:
  value: 98
decay_rate:
  value: 1.6581182497160325
decay_steps:
  value: 358
dense1_size:
  value: 46
dense2_size:
  value: 82
dropout:
  value: 0.2609878592253574
epoch:
  value: 11
initial_learning_rate:
  value: 9.250941326697524e-05
log_freq:
  value: 1
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0020614964993199976
optimizer:
  value: sgd
patience:
  value: 8
random_seed:
  value: 80
staircase:
  value: 'true'
validation_split:
  value: 0.1077673582430466
verbose:
  value: 4
