wandb_version: 1

activation_3:
  value: sigmoid
activation_4:
  value: sigmoid
batch_size:
  value: 32
decay_rate:
  value: 1.1692047194658597
decay_steps:
  value: 463
dense1_size:
  value: 133
dense2_size:
  value: 70
dropout:
  value: 0.3445170298502309
epoch:
  value: 23
initial_learning_rate:
  value: 0.0015748155140663733
log_freq:
  value: 2
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0020617532406587823
optimizer:
  value: sgd
patience:
  value: 12
random_seed:
  value: 53
staircase:
  value: 'false'
validation_split:
  value: 0.6644218997544352
verbose:
  value: 2
