wandb_version: 1

activation_3:
  value: sigmoid
activation_4:
  value: sigmoid
batch_size:
  value: 63
decay_rate:
  value: 1.683668616598603
decay_steps:
  value: 351
dense1_size:
  value: 158
dense2_size:
  value: 86
dropout:
  value: 0.33568084497813555
epoch:
  value: 14
initial_learning_rate:
  value: 0.0008397724236614734
log_freq:
  value: 2
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0015527442228702325
optimizer:
  value: sgd
patience:
  value: 13
random_seed:
  value: 79
staircase:
  value: 'true'
validation_split:
  value: 0.5390766378021975
verbose:
  value: 1
