wandb_version: 1

activation_3:
  value: sigmoid
activation_4:
  value: sigmoid
batch_size:
  value: 65
decay_rate:
  value: 1.5719787371163358
decay_steps:
  value: 248
dense1_size:
  value: 130
dense2_size:
  value: 80
dropout:
  value: 0.3640342335288046
epoch:
  value: 23
initial_learning_rate:
  value: 0.003393451601752268
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0037042625607115543
optimizer:
  value: sgd
patience:
  value: 6
random_seed:
  value: 81
staircase:
  value: 'true'
validation_split:
  value: 0.2799832943899835
verbose:
  value: 4
