wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 39
decay_rate:
  value: 0.70989914935965
decay_steps:
  value: 571
dense1_size:
  value: 70
dense2_size:
  value: 49
dropout:
  value: 0.3786215534588976
epoch:
  value: 13
initial_learning_rate:
  value: 0.0009944128442791
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001318200750927649
optimizer:
  value: adadelta
patience:
  value: 13
random_seed:
  value: 69
staircase:
  value: 'true'
validation_split:
  value: 0.28199662984674356
verbose:
  value: 1
