wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 29
decay_rate:
  value: 0.5689262420662358
decay_steps:
  value: 308
dense1_size:
  value: 69
dense2_size:
  value: 33
dropout:
  value: 0.1330701292768203
epoch:
  value: 5
initial_learning_rate:
  value: 0.0010850094315177376
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001961227435464307
optimizer:
  value: adadelta
patience:
  value: 8
random_seed:
  value: 46
staircase:
  value: 'false'
validation_split:
  value: 0.3576100832467404
verbose:
  value: 1
