wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 44
decay_rate:
  value: 0.833881840176674
decay_steps:
  value: 354
dense1_size:
  value: 128
dense2_size:
  value: 51
dropout:
  value: 0.01402969120454354
epoch:
  value: 13
initial_learning_rate:
  value: 0.000288329010608496
log_freq:
  value: 2
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0013927234958658254
optimizer:
  value: adamax
patience:
  value: 15
random_seed:
  value: 55
staircase:
  value: 'true'
validation_split:
  value: 0.32372913472608544
verbose:
  value: 1
