wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 44
decay_rate:
  value: 0.3820168230175297
decay_steps:
  value: 597
dense1_size:
  value: 71
dense2_size:
  value: 37
dropout:
  value: 0.3189994020871439
epoch:
  value: 12
initial_learning_rate:
  value: 0.000173823393721907
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0012716695246455805
optimizer:
  value: sgd
patience:
  value: 10
random_seed:
  value: 27
staircase:
  value: 'true'
validation_split:
  value: 0.17537034846066227
verbose:
  value: 1
