wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 32
decay_rate:
  value: 0.4876120565003881
decay_steps:
  value: 506
dense1_size:
  value: 81
dense2_size:
  value: 33
dropout:
  value: 0.2857542235053987
epoch:
  value: 8
initial_learning_rate:
  value: 0.000449030742879449
log_freq:
  value: 2
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0008224899743729448
optimizer:
  value: adadelta
patience:
  value: 11
random_seed:
  value: 35
staircase:
  value: 'false'
validation_split:
  value: 0.295642252626588
verbose:
  value: 2
