wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 38
decay_rate:
  value: 0.9662977439478434
decay_steps:
  value: 375
dense1_size:
  value: 94
dense2_size:
  value: 33
dropout:
  value: 0.3476261774844871
epoch:
  value: 16
initial_learning_rate:
  value: 0.001545458701315487
log_freq:
  value: 1
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.001146974763122411
optimizer:
  value: adadelta
patience:
  value: 12
random_seed:
  value: 55
staircase:
  value: 'false'
validation_split:
  value: 0.1450985645813729
verbose:
  value: 1
