wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 36
decay_rate:
  value: 0.829483126580538
decay_steps:
  value: 383
dense1_size:
  value: 68
dense2_size:
  value: 62
dropout:
  value: 0.30091895481275455
epoch:
  value: 13
initial_learning_rate:
  value: 0.0011079444427226253
log_freq:
  value: 1
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0008056261811100416
optimizer:
  value: sgd
patience:
  value: 3
random_seed:
  value: 23
staircase:
  value: 'true'
validation_split:
  value: 0.12959832259323645
verbose:
  value: 1
