wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 45
decay_rate:
  value: 0.9726388861452462
decay_steps:
  value: 542
dense1_size:
  value: 78
dense2_size:
  value: 39
dropout:
  value: 0.319598213572474
epoch:
  value: 13
initial_learning_rate:
  value: 0.00025748447469527483
log_freq:
  value: 2
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0005523006733301701
optimizer:
  value: adamax
patience:
  value: 11
random_seed:
  value: 57
staircase:
  value: 'false'
validation_split:
  value: 0.2614786071585644
verbose:
  value: 2
