wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 63
decay_rate:
  value: 0.8797765982713521
decay_steps:
  value: 167
dense1_size:
  value: 80
dense2_size:
  value: 28
dropout:
  value: 0.17932853229656098
epoch:
  value: 10
initial_learning_rate:
  value: 0.00046408797749497354
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0019721873260176263
optimizer:
  value: adamax
patience:
  value: 3
random_seed:
  value: 29
staircase:
  value: 'false'
validation_split:
  value: 0.3402001975897538
verbose:
  value: 2
