wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 29
decay_rate:
  value: 0.875333833909955
decay_steps:
  value: 364
dense1_size:
  value: 43
dense2_size:
  value: 16
dropout:
  value: 0.06011854191003305
epoch:
  value: 10
initial_learning_rate:
  value: 0.001963680951214956
log_freq:
  value: 1
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0015217246509559477
optimizer:
  value: sgd
patience:
  value: 15
random_seed:
  value: 29
staircase:
  value: 'true'
validation_split:
  value: 0.23674755846881976
verbose:
  value: 1
