wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 51
decay_rate:
  value: 0.7021165741014885
decay_steps:
  value: 271
dense1_size:
  value: 100
dense2_size:
  value: 22
dropout:
  value: 0.3760778985981621
epoch:
  value: 14
initial_learning_rate:
  value: 0.001760306825525442
log_freq:
  value: 2
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0016410834251289893
optimizer:
  value: adadelta
patience:
  value: 5
random_seed:
  value: 57
staircase:
  value: 'true'
validation_split:
  value: 0.10553435193168248
verbose:
  value: 2
