wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 44
decay_rate:
  value: 0.3216233535145724
decay_steps:
  value: 545
dense1_size:
  value: 76
dense2_size:
  value: 29
dropout:
  value: 0.3220787225888213
epoch:
  value: 8
initial_learning_rate:
  value: 0.00021965893370769785
log_freq:
  value: 2
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0007653059005654148
optimizer:
  value: sgd
patience:
  value: 5
random_seed:
  value: 39
staircase:
  value: 'true'
validation_split:
  value: 0.3831850261360983
verbose:
  value: 2
