wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 26
decay_rate:
  value: 0.3424775429897855
decay_steps:
  value: 422
dense1_size:
  value: 104
dense2_size:
  value: 26
dropout:
  value: 0.16779496929425708
epoch:
  value: 16
initial_learning_rate:
  value: 0.0009536422262047242
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001881141095717147
optimizer:
  value: adadelta
patience:
  value: 6
random_seed:
  value: 30
staircase:
  value: 'false'
validation_split:
  value: 0.18378284233508943
verbose:
  value: 2
