wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 53
decay_rate:
  value: 0.540180910080301
decay_steps:
  value: 279
dense1_size:
  value: 60
dense2_size:
  value: 52
dropout:
  value: 0.0973099916095476
epoch:
  value: 14
initial_learning_rate:
  value: 0.0010375370754477635
log_freq:
  value: 1
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0010729973033050805
optimizer:
  value: sgd
patience:
  value: 7
random_seed:
  value: 68
staircase:
  value: 'true'
validation_split:
  value: 0.2190042681061608
verbose:
  value: 1
