wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 56
decay_rate:
  value: 0.5657263392345914
decay_steps:
  value: 565
dense1_size:
  value: 36
dense2_size:
  value: 16
dropout:
  value: 0.31204531413977216
epoch:
  value: 8
initial_learning_rate:
  value: 0.000620349354829959
log_freq:
  value: 1
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0006354259874977975
optimizer:
  value: sgd
patience:
  value: 4
random_seed:
  value: 67
staircase:
  value: 'true'
validation_split:
  value: 0.26727245758068163
verbose:
  value: 2
