wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 16
decay_rate:
  value: 0.9430496090763374
decay_steps:
  value: 317
dense1_size:
  value: 53
dense2_size:
  value: 23
dropout:
  value: 0.37723970564212994
epoch:
  value: 16
initial_learning_rate:
  value: 9.647640829591244e-05
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0019552740793772677
optimizer:
  value: adadelta
patience:
  value: 10
random_seed:
  value: 51
staircase:
  value: 'false'
validation_split:
  value: 0.24844074831818977
verbose:
  value: 2
