wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 41
decay_rate:
  value: 0.6478015647814779
decay_steps:
  value: 448
dense1_size:
  value: 94
dense2_size:
  value: 57
dropout:
  value: 0.2303234749183427
epoch:
  value: 7
initial_learning_rate:
  value: 0.0015956501688421888
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0009920634481056971
optimizer:
  value: adam
patience:
  value: 4
random_seed:
  value: 81
staircase:
  value: 'false'
validation_split:
  value: 0.2628589660718912
verbose:
  value: 2
