wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 48
decay_rate:
  value: 0.5821075597512064
decay_steps:
  value: 298
dense1_size:
  value: 93
dense2_size:
  value: 18
dropout:
  value: 0.33667642589655955
epoch:
  value: 5
initial_learning_rate:
  value: 0.0018784036497460216
log_freq:
  value: 1
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.001775834761194973
optimizer:
  value: adamax
patience:
  value: 7
random_seed:
  value: 72
staircase:
  value: 'false'
validation_split:
  value: 0.39859316772027287
verbose:
  value: 1
