wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 40
decay_rate:
  value: 0.3243363839848543
decay_steps:
  value: 474
dense1_size:
  value: 109
dense2_size:
  value: 63
dropout:
  value: 0.24134474314194787
epoch:
  value: 8
initial_learning_rate:
  value: 0.00094316869520552
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0007014506266253503
optimizer:
  value: adadelta
patience:
  value: 8
random_seed:
  value: 80
staircase:
  value: 'false'
validation_split:
  value: 0.13107614859568018
verbose:
  value: 2
