wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 53
decay_rate:
  value: 0.9307098748053314
decay_steps:
  value: 509
dense1_size:
  value: 45
dense2_size:
  value: 26
dropout:
  value: 0.00269260592082512
epoch:
  value: 11
initial_learning_rate:
  value: 0.0005450762863292793
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0015566716789202656
optimizer:
  value: adamax
patience:
  value: 8
random_seed:
  value: 74
staircase:
  value: 'false'
validation_split:
  value: 0.20363242509800608
verbose:
  value: 2
