wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 30
decay_rate:
  value: 0.8591432085105676
decay_steps:
  value: 273
dense1_size:
  value: 85
dense2_size:
  value: 34
dropout:
  value: 0.2581452524911895
epoch:
  value: 9
initial_learning_rate:
  value: 0.0005730628434161139
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0006256707653309754
optimizer:
  value: adam
patience:
  value: 6
random_seed:
  value: 43
staircase:
  value: 'false'
validation_split:
  value: 0.2229481651427282
verbose:
  value: 1
