wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 30
decay_rate:
  value: 0.5733219771549642
decay_steps:
  value: 509
dense1_size:
  value: 98
dense2_size:
  value: 32
dropout:
  value: 0.018085060180852076
epoch:
  value: 14
initial_learning_rate:
  value: 4.0025030588223026e-05
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0005784228575260368
optimizer:
  value: adam
patience:
  value: 3
random_seed:
  value: 36
staircase:
  value: 'false'
validation_split:
  value: 0.2922737791188012
verbose:
  value: 1
