wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 64
decay_rate:
  value: 0.5151904886381163
decay_steps:
  value: 575
dense1_size:
  value: 39
dense2_size:
  value: 56
dropout:
  value: 0.2957267368655967
epoch:
  value: 16
initial_learning_rate:
  value: 0.001847364060178045
log_freq:
  value: 1
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0016737342411853584
optimizer:
  value: adadelta
patience:
  value: 8
random_seed:
  value: 36
staircase:
  value: 'false'
validation_split:
  value: 0.39730872365492664
verbose:
  value: 1
