wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 43
decay_rate:
  value: 0.8651295308458689
decay_steps:
  value: 240
dense1_size:
  value: 59
dense2_size:
  value: 27
dropout:
  value: 0.17991632587403902
epoch:
  value: 14
initial_learning_rate:
  value: 0.0006872668229445737
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0018382104024141984
optimizer:
  value: adam
patience:
  value: 7
random_seed:
  value: 34
staircase:
  value: 'false'
validation_split:
  value: 0.32196574233578035
verbose:
  value: 2
