wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 59
decay_rate:
  value: 0.5299604207775617
decay_steps:
  value: 184
dense1_size:
  value: 61
dense2_size:
  value: 57
dropout:
  value: 0.1411444541496489
epoch:
  value: 6
initial_learning_rate:
  value: 0.0019157303261452252
log_freq:
  value: 1
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0008092385976290364
optimizer:
  value: adamax
patience:
  value: 6
random_seed:
  value: 59
staircase:
  value: 'true'
validation_split:
  value: 0.15944516344734933
verbose:
  value: 1
