wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 33
decay_rate:
  value: 0.5877114101405037
decay_steps:
  value: 212
dense1_size:
  value: 105
dense2_size:
  value: 18
dropout:
  value: 0.15077304025736546
epoch:
  value: 14
initial_learning_rate:
  value: 0.0015294672880989209
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0005478721507091819
optimizer:
  value: adam
patience:
  value: 7
random_seed:
  value: 50
staircase:
  value: 'true'
validation_split:
  value: 0.2309468002653667
verbose:
  value: 1
