wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 48
decay_rate:
  value: 0.9354470457596036
decay_steps:
  value: 389
dense1_size:
  value: 106
dense2_size:
  value: 16
dropout:
  value: 0.08724894088808788
epoch:
  value: 15
initial_learning_rate:
  value: 0.0018542022630834815
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0006034726351122577
optimizer:
  value: adamax
patience:
  value: 7
random_seed:
  value: 31
staircase:
  value: 'true'
validation_split:
  value: 0.3738950985030125
verbose:
  value: 1
