wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 60
decay_rate:
  value: 0.9462963144295848
decay_steps:
  value: 326
dense1_size:
  value: 111
dense2_size:
  value: 59
dropout:
  value: 0.08166422574581272
epoch:
  value: 4
initial_learning_rate:
  value: 0.0019112706281888797
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0008497737778357832
optimizer:
  value: adamax
patience:
  value: 10
random_seed:
  value: 67
staircase:
  value: 'true'
validation_split:
  value: 0.33737678345158606
verbose:
  value: 2
