wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 63
decay_rate:
  value: 0.5709484778759308
decay_steps:
  value: 425
dense1_size:
  value: 62
dense2_size:
  value: 25
dropout:
  value: 0.25308852706461654
epoch:
  value: 12
initial_learning_rate:
  value: 0.001000792670701765
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001129397986733509
optimizer:
  value: sgd
patience:
  value: 10
random_seed:
  value: 45
staircase:
  value: 'false'
validation_split:
  value: 0.11534450105060598
verbose:
  value: 2
