wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 61
decay_rate:
  value: 0.5546963560531953
decay_steps:
  value: 347
dense1_size:
  value: 34
dense2_size:
  value: 44
dropout:
  value: 0.2651340622600766
epoch:
  value: 7
initial_learning_rate:
  value: 0.001175608828877664
log_freq:
  value: 2
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0012805067384722762
optimizer:
  value: adamax
patience:
  value: 13
random_seed:
  value: 73
staircase:
  value: 'false'
validation_split:
  value: 0.22169015963175057
verbose:
  value: 2
