wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 53
decay_rate:
  value: 0.5482948343735257
decay_steps:
  value: 571
dense1_size:
  value: 67
dense2_size:
  value: 60
dropout:
  value: 0.3930649976454195
epoch:
  value: 10
initial_learning_rate:
  value: 0.0012557273249794035
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0005759407405466937
optimizer:
  value: sgd
patience:
  value: 3
random_seed:
  value: 62
staircase:
  value: 'true'
validation_split:
  value: 0.2662984625870747
verbose:
  value: 2
