wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 21
decay_rate:
  value: 0.557416454212084
decay_steps:
  value: 487
dense1_size:
  value: 110
dense2_size:
  value: 19
dropout:
  value: 0.3961737776491735
epoch:
  value: 10
initial_learning_rate:
  value: 0.0017965066920521391
log_freq:
  value: 2
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0009731815200106654
optimizer:
  value: adam
patience:
  value: 5
random_seed:
  value: 52
staircase:
  value: 'false'
validation_split:
  value: 0.163396582993137
verbose:
  value: 1
