wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 31
decay_rate:
  value: 0.6334979884301488
decay_steps:
  value: 532
dense1_size:
  value: 34
dense2_size:
  value: 40
dropout:
  value: 0.24299492643354095
epoch:
  value: 6
initial_learning_rate:
  value: 0.0001220686520381365
log_freq:
  value: 1
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0008063520917986951
optimizer:
  value: adam
patience:
  value: 10
random_seed:
  value: 45
staircase:
  value: 'true'
validation_split:
  value: 0.16221576994466905
verbose:
  value: 2
