wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 48
decay_rate:
  value: 0.6862929806156763
decay_steps:
  value: 515
dense1_size:
  value: 45
dense2_size:
  value: 45
dropout:
  value: 0.37667849428753863
epoch:
  value: 5
initial_learning_rate:
  value: 0.0016445976823212546
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0006467697950068667
optimizer:
  value: sgd
patience:
  value: 4
random_seed:
  value: 42
staircase:
  value: 'true'
validation_split:
  value: 0.11183781858232134
verbose:
  value: 1
