wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
batch_size:
  value: 35
conv1_filters:
  value: 4
conv1_kernelsize:
  value: 6
conv2_filters:
  value: 13
conv2_kernelsize:
  value: 6
decay_rate:
  value: 0.6852971858231952
decay_steps:
  value: 212
dense1_size:
  value: 70
dropout:
  value: 0.2285282153152773
epoch:
  value: 7
initial_learning_rate:
  value: 9.500128162212966e-05
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0017161227229534877
optimizer:
  value: sgd
patience:
  value: 13
staircase:
  value: 'true'
validation_split:
  value: 0.11938662134163858
verbose:
  value: 2
