wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
batch_size:
  value: 43
conv1_filters:
  value: 7
conv1_kernelsize:
  value: 10
conv2_filters:
  value: 9
conv2_kernelsize:
  value: 3
decay_rate:
  value: 0.7084365627984961
decay_steps:
  value: 188
dense1_size:
  value: 66
dropout:
  value: 0.29911895263612004
epoch:
  value: 4
initial_learning_rate:
  value: 4.082516150500944e-05
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0018651938154140072
optimizer:
  value: sgd
patience:
  value: 10
staircase:
  value: 'false'
validation_split:
  value: 0.3954502018796461
verbose:
  value: 1
