wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
batch_size:
  value: 55
conv1_filters:
  value: 14
conv1_kernelsize:
  value: 4
conv2_filters:
  value: 24
conv2_kernelsize:
  value: 4
decay_rate:
  value: 0.4860881425915547
decay_steps:
  value: 530
dense1_size:
  value: 82
dropout:
  value: 0.2876717493293388
epoch:
  value: 6
initial_learning_rate:
  value: 0.00017657013661625943
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0011620704472478267
optimizer:
  value: sgd
patience:
  value: 34
staircase:
  value: 'false'
validation_split:
  value: 0.14729429227992216
verbose:
  value: 2
