wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
batch_size:
  value: 17
conv1_filters:
  value: 5
conv1_kernelsize:
  value: 6
conv2_filters:
  value: 24
conv2_kernelsize:
  value: 6
decay_rate:
  value: 0.8009779432191604
decay_steps:
  value: 586
dense1_size:
  value: 35
dropout:
  value: 0.39781479181467183
epoch:
  value: 10
initial_learning_rate:
  value: 2.0096212542926932e-05
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0011011934989791049
optimizer:
  value: sgd
patience:
  value: 20
staircase:
  value: 'true'
validation_split:
  value: 0.27125582116071856
verbose:
  value: 2
