wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
batch_size:
  value: 41
conv1_filters:
  value: 16
conv1_kernelsize:
  value: 9
conv2_filters:
  value: 29
conv2_kernelsize:
  value: 4
decay_rate:
  value: 0.4413376218649643
decay_steps:
  value: 444
dense1_size:
  value: 90
dropout:
  value: 0.3414451357487569
epoch:
  value: 11
initial_learning_rate:
  value: 7.192741890276471e-05
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001443650500165438
optimizer:
  value: sgd
patience:
  value: 6
staircase:
  value: 'false'
validation_split:
  value: 0.376813462339025
verbose:
  value: 2
