wandb_version: 1

activation_3:
  value: sigmoid
activation_4:
  value: sigmoid
batch_size:
  value: 30
decay_rate:
  value: 0.6498839256388214
decay_steps:
  value: 600
dense1_size:
  value: 52
dense2_size:
  value: 97
dropout:
  value: 0.37477504064785494
epoch:
  value: 25
initial_learning_rate:
  value: 0.002911453490209871
log_freq:
  value: 2
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.003405695683090428
optimizer:
  value: sgd
patience:
  value: 9
staircase:
  value: 'false'
validation_split:
  value: 0.17193688045926006
verbose:
  value: 4
