wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1672953906.173224
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 23
      - 37
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_3:
  desc: null
  value: relu
activation_4:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 101
dense1_size:
  desc: null
  value: 133
dense2_size:
  desc: null
  value: 76
dropout:
  desc: null
  value: 0.3912792564061651
epoch:
  desc: null
  value: 14
initial_learning_rate:
  desc: null
  value: 0.0035843945906284505
loss:
  desc: null
  value: mean_squared_error
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.000887772532527264
validation_split:
  desc: null
  value: 0.2453009449589635
