wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1672943637.701563
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 23
      - 37
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_3:
  desc: null
  value: relu
activation_4:
  desc: null
  value: tanh
batch_size:
  desc: null
  value: 40
conv1_filters:
  desc: null
  value: 16
conv1_kernelsize:
  desc: null
  value: 7
conv2_filters:
  desc: null
  value: 28
conv2_kernelsize:
  desc: null
  value: 2
decay_rate:
  desc: null
  value: 1.4819283621522463
decay_steps:
  desc: null
  value: 482
dense1_size:
  desc: null
  value: 86
dense2_size:
  desc: null
  value: 43
dropout:
  desc: null
  value: 0.19343081361021291
epoch:
  desc: null
  value: 27
initial_learning_rate:
  desc: null
  value: 0.0029556257944777977
log_freq:
  desc: null
  value: 2
loss:
  desc: null
  value: mean_squared_error
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.002831554243989333
optimizer:
  desc: null
  value: adam
patience:
  desc: null
  value: 14
staircase:
  desc: null
  value: 'true'
validation_split:
  desc: null
  value: 0.3675113872988433
verbose:
  desc: null
  value: 2
