wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: batch/batch_step
      6:
      - 3
    - 1: batch/loss
      5: 1
      6:
      - 1
    - 1: batch/accuracy
      5: 1
      6:
      - 1
    - 1: batch/learning_rate
      5: 1
      6:
      - 1
    python_version: 3.9.6
    start_time: 1672953041.125933
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 7
      - 23
      - 37
      - 38
      - 39
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_3:
  desc: null
  value: sigmoid
activation_4:
  desc: null
  value: sigmoid
batch_size:
  desc: null
  value: 38
decay_rate:
  desc: null
  value: 1.3382383844485712
decay_steps:
  desc: null
  value: 220
dense1_size:
  desc: null
  value: 150
dense2_size:
  desc: null
  value: 54
dropout:
  desc: null
  value: 0.3724079136969704
epoch:
  desc: null
  value: 14
initial_learning_rate:
  desc: null
  value: 0.002251656166407609
log_freq:
  desc: null
  value: 2
loss:
  desc: null
  value: categorical_crossentropy
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.0008429575521818138
optimizer:
  desc: null
  value: sgd
patience:
  desc: null
  value: 14
random_seed:
  desc: null
  value: 30
staircase:
  desc: null
  value: 'false'
validation_split:
  desc: null
  value: 0.5791774783932438
verbose:
  desc: null
  value: 3
