wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1672939917.705973
    t:
      1:
      - 2
      - 3
      - 55
      3:
      - 23
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
