wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.6
    start_time: 1672943664.312007
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 23
      - 37
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_3:
  desc: null
  value: tanh
activation_4:
  desc: null
  value: sigmoid
batch_size:
  desc: null
  value: 77
conv1_filters:
  desc: null
  value: 5
conv1_kernelsize:
  desc: null
  value: 5
conv2_filters:
  desc: null
  value: 21
conv2_kernelsize:
  desc: null
  value: 5
decay_rate:
  desc: null
  value: 1.3432660347787568
decay_steps:
  desc: null
  value: 327
dense1_size:
  desc: null
  value: 152
dense2_size:
  desc: null
  value: 35
dropout:
  desc: null
  value: 0.1826600981958459
epoch:
  desc: null
  value: 20
initial_learning_rate:
  desc: null
  value: 0.001762522223066803
log_freq:
  desc: null
  value: 2
loss:
  desc: null
  value: categorical_crossentropy
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.0034823546829075005
optimizer:
  desc: null
  value: sgd
patience:
  desc: null
  value: 12
staircase:
  desc: null
  value: 'true'
validation_split:
  desc: null
  value: 0.5418781033997788
verbose:
  desc: null
  value: 2
