wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 21
conv1_filters:
  value: 6
conv1_kernelsize:
  value: 10
conv2_filters:
  value: 14
conv2_kernelsize:
  value: 5
decay_rate:
  value: 0.48678541406536247
decay_steps:
  value: 366
dense1_size:
  value: 112
dropout:
  value: 0.9136346515992456
epoch:
  value: 6
epochs:
  value: 13
initial_learning_rate:
  value: 1.9761226093188492e-06
layer_1:
  value: 579
layer_2:
  value: 5
learning_rate:
  value: 0.0006194581432861989
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001030666110545338
optimizer:
  value: sgd
patience:
  value: 3
random_seed:
  value: 33
staircase:
  value: 'true'
validation_split:
  value: 0.17385216891178268
verbose:
  value: 2
