wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 54
conv1_filters:
  value: 4
conv1_kernelsize:
  value: 3
conv2_filters:
  value: 25
conv2_kernelsize:
  value: 4
decay_rate:
  value: 0.5962803366391329
decay_steps:
  value: 370
dense1_size:
  value: 34
dropout:
  value: 0.9798247672590118
epoch:
  value: 14
epochs:
  value: 17
initial_learning_rate:
  value: 9.372690957248496e-07
layer_1:
  value: 392
layer_2:
  value: 6
learning_rate:
  value: 0.0015759208722288258
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.00137001312903117
optimizer:
  value: sgd
patience:
  value: 8
random_seed:
  value: 82
staircase:
  value: 'false'
validation_split:
  value: 0.3747488199503326
verbose:
  value: 2
