wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 56
conv1_filters:
  value: 16
conv1_kernelsize:
  value: 3
conv2_filters:
  value: 24
conv2_kernelsize:
  value: 6
decay_rate:
  value: 0.8772731811237032
decay_steps:
  value: 404
dense1_size:
  value: 88
dropout:
  value: 0.4402097468382753
epoch:
  value: 16
epochs:
  value: 7
initial_learning_rate:
  value: 7.905373951730907e-07
layer_1:
  value: 956
layer_2:
  value: 19
learning_rate:
  value: 0.001349768287742531
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0008371647236841404
optimizer:
  value: sgd
patience:
  value: 3
random_seed:
  value: 30
staircase:
  value: 'true'
validation_split:
  value: 0.15708608061201185
verbose:
  value: 1
