wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 44
conv1_filters:
  value: 4
conv1_kernelsize:
  value: 8
conv2_filters:
  value: 10
conv2_kernelsize:
  value: 2
decay_rate:
  value: 0.8088755474529389
decay_steps:
  value: 255
dense1_size:
  value: 47
dropout:
  value: 0.2215261074769944
epoch:
  value: 10
epochs:
  value: 14
initial_learning_rate:
  value: 6.353090945455622e-07
layer_1:
  value: 994
layer_2:
  value: 18
learning_rate:
  value: 0.0018299105820588088
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0014580878254842142
optimizer:
  value: sgd
patience:
  value: 9
random_seed:
  value: 40
staircase:
  value: 'true'
validation_split:
  value: 0.3631237859374222
verbose:
  value: 1
