wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 45
conv1_filters:
  value: 5
conv1_kernelsize:
  value: 7
conv2_filters:
  value: 9
conv2_kernelsize:
  value: 3
decay_rate:
  value: 0.4248367445425185
decay_steps:
  value: 245
dense1_size:
  value: 86
dropout:
  value: 1.0774115481159474
epoch:
  value: 15
epochs:
  value: 19
initial_learning_rate:
  value: 1.8578274854348177e-06
layer_1:
  value: 649
layer_2:
  value: 11
learning_rate:
  value: 0.0005464523311553106
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0018569573127236692
optimizer:
  value: sgd
patience:
  value: 7
random_seed:
  value: 25
staircase:
  value: 'false'
validation_split:
  value: 0.22877525852325373
verbose:
  value: 1
