wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 58
conv1_filters:
  value: 12
conv1_kernelsize:
  value: 9
conv2_filters:
  value: 16
conv2_kernelsize:
  value: 4
decay_rate:
  value: 0.5277153635181826
decay_steps:
  value: 531
dense1_size:
  value: 110
dropout:
  value: 0.36844778615157026
epoch:
  value: 6
epochs:
  value: 16
initial_learning_rate:
  value: 1.375607722345704e-06
layer_1:
  value: 448
layer_2:
  value: 11
learning_rate:
  value: 0.0011550218092786157
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0016310956954028808
optimizer:
  value: sgd
patience:
  value: 9
random_seed:
  value: 75
staircase:
  value: 'false'
validation_split:
  value: 0.1925468366090825
verbose:
  value: 1
