wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 64
conv1_filters:
  value: 5
conv1_kernelsize:
  value: 3
conv2_filters:
  value: 9
conv2_kernelsize:
  value: 6
decay_rate:
  value: 0.9302133714167108
decay_steps:
  value: 179
dense1_size:
  value: 119
dropout:
  value: 0.9309008962837472
epoch:
  value: 15
epochs:
  value: 17
initial_learning_rate:
  value: 1.539471846549081e-06
layer_1:
  value: 677
layer_2:
  value: 18
learning_rate:
  value: 0.001448178324809317
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0005123116798227601
optimizer:
  value: sgd
patience:
  value: 8
random_seed:
  value: 51
staircase:
  value: 'true'
validation_split:
  value: 0.12120800818986092
verbose:
  value: 2
