wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 48
conv1_filters:
  value: 4
conv1_kernelsize:
  value: 5
conv2_filters:
  value: 32
conv2_kernelsize:
  value: 6
decay_rate:
  value: 0.9270371918820468
decay_steps:
  value: 230
dense1_size:
  value: 34
dropout:
  value: 0.734374333472944
epoch:
  value: 5
epochs:
  value: 7
initial_learning_rate:
  value: 1.4867101202658315e-06
layer_1:
  value: 862
layer_2:
  value: 19
learning_rate:
  value: 0.0016747954926093543
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0012243360069752263
optimizer:
  value: sgd
patience:
  value: 9
random_seed:
  value: 23
staircase:
  value: 'false'
validation_split:
  value: 0.16796133783603323
verbose:
  value: 2
