wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 35
conv1_filters:
  value: 14
conv1_kernelsize:
  value: 5
conv2_filters:
  value: 24
conv2_kernelsize:
  value: 3
decay_rate:
  value: 0.6551621627000683
decay_steps:
  value: 513
dense1_size:
  value: 41
dropout:
  value: 1.2761458904932488
epoch:
  value: 11
epochs:
  value: 13
initial_learning_rate:
  value: 1.5949160698892835e-06
layer_1:
  value: 311
layer_2:
  value: 20
learning_rate:
  value: 0.0013286955925707945
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0009860196422356569
optimizer:
  value: sgd
patience:
  value: 3
random_seed:
  value: 31
staircase:
  value: 'true'
validation_split:
  value: 0.12741495969832986
verbose:
  value: 1
