wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 46
conv1_filters:
  value: 12
conv1_kernelsize:
  value: 3
conv2_filters:
  value: 15
conv2_kernelsize:
  value: 5
decay_rate:
  value: 0.34505693845080826
decay_steps:
  value: 574
dense1_size:
  value: 122
dropout:
  value: 0.4477626302993564
epoch:
  value: 12
epochs:
  value: 9
initial_learning_rate:
  value: 1.151217640933898e-06
layer_1:
  value: 654
layer_2:
  value: 10
learning_rate:
  value: 0.0005292727604230955
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001988325592068432
optimizer:
  value: sgd
patience:
  value: 10
random_seed:
  value: 57
staircase:
  value: 'false'
validation_split:
  value: 0.33813017714817595
verbose:
  value: 1
