wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 44
conv1_filters:
  value: 16
conv1_kernelsize:
  value: 5
conv2_filters:
  value: 28
conv2_kernelsize:
  value: 5
decay_rate:
  value: 0.8681346625067832
decay_steps:
  value: 578
dense1_size:
  value: 107
dropout:
  value: 0.8644086786349611
epoch:
  value: 15
epochs:
  value: 7
initial_learning_rate:
  value: 1.958556047735187e-06
layer_1:
  value: 490
layer_2:
  value: 19
learning_rate:
  value: 0.0016119998650220122
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0005549227680309858
optimizer:
  value: sgd
patience:
  value: 8
random_seed:
  value: 31
staircase:
  value: 'true'
validation_split:
  value: 0.1928835079263004
verbose:
  value: 2
