wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 38
conv1_filters:
  value: 10
conv1_kernelsize:
  value: 3
conv2_filters:
  value: 30
conv2_kernelsize:
  value: 2
decay_rate:
  value: 0.6046267284978442
decay_steps:
  value: 469
dense1_size:
  value: 128
dropout:
  value: 0.8699035644337129
epoch:
  value: 7
epochs:
  value: 18
initial_learning_rate:
  value: 1.023885628337734e-06
layer_1:
  value: 713
layer_2:
  value: 18
learning_rate:
  value: 0.0009278322174962716
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0017046548187198492
optimizer:
  value: sgd
patience:
  value: 6
random_seed:
  value: 83
staircase:
  value: 'false'
validation_split:
  value: 0.13950688239309528
verbose:
  value: 2
