wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 62
conv1_filters:
  value: 16
conv1_kernelsize:
  value: 8
conv2_filters:
  value: 27
conv2_kernelsize:
  value: 6
decay_rate:
  value: 0.701509139601578
decay_steps:
  value: 221
dense1_size:
  value: 76
dropout:
  value: 0.9857646160982108
epoch:
  value: 10
epochs:
  value: 9
initial_learning_rate:
  value: 1.8149987050014256e-06
layer_1:
  value: 432
layer_2:
  value: 14
learning_rate:
  value: 0.0019517063410215711
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.000501758246847301
optimizer:
  value: sgd
patience:
  value: 4
random_seed:
  value: 74
staircase:
  value: 'true'
validation_split:
  value: 0.1882386557375196
verbose:
  value: 2
