wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 52
conv1_filters:
  value: 12
conv1_kernelsize:
  value: 5
conv2_filters:
  value: 31
conv2_kernelsize:
  value: 5
decay_rate:
  value: 0.7524213551551826
decay_steps:
  value: 361
dense1_size:
  value: 99
dropout:
  value: 0.554010512010992
epoch:
  value: 7
epochs:
  value: 16
initial_learning_rate:
  value: 1.049367992889204e-06
layer_1:
  value: 386
layer_2:
  value: 15
learning_rate:
  value: 0.001301706182591757
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001680617769313876
optimizer:
  value: sgd
patience:
  value: 10
random_seed:
  value: 28
staircase:
  value: 'false'
validation_split:
  value: 0.21578119593978323
verbose:
  value: 1
