wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 39
conv1_filters:
  value: 8
conv1_kernelsize:
  value: 10
conv2_filters:
  value: 30
conv2_kernelsize:
  value: 3
decay_rate:
  value: 0.7190814956766283
decay_steps:
  value: 465
dense1_size:
  value: 63
dropout:
  value: 0.8918371592989215
epoch:
  value: 12
epochs:
  value: 5
initial_learning_rate:
  value: 1.6055869009025482e-06
layer_1:
  value: 595
layer_2:
  value: 7
learning_rate:
  value: 0.0009718945450842668
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0012250475770257737
optimizer:
  value: sgd
patience:
  value: 3
random_seed:
  value: 77
staircase:
  value: 'false'
validation_split:
  value: 0.18691972288706557
verbose:
  value: 2
