wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 64
conv1_filters:
  value: 16
conv1_kernelsize:
  value: 6
conv2_filters:
  value: 13
conv2_kernelsize:
  value: 5
decay_rate:
  value: 0.3934372194342032
decay_steps:
  value: 361
dense1_size:
  value: 99
dropout:
  value: 0.9093399503665348
epoch:
  value: 10
epochs:
  value: 8
initial_learning_rate:
  value: 1.8744991982495972e-06
layer_1:
  value: 832
layer_2:
  value: 10
learning_rate:
  value: 0.0007772061696034501
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0014576103862365465
optimizer:
  value: sgd
patience:
  value: 4
random_seed:
  value: 64
staircase:
  value: 'true'
validation_split:
  value: 0.14138139732694893
verbose:
  value: 2
