wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 37
conv1_filters:
  value: 9
conv1_kernelsize:
  value: 8
conv2_filters:
  value: 27
conv2_kernelsize:
  value: 5
decay_rate:
  value: 0.679113049500992
decay_steps:
  value: 239
dense1_size:
  value: 114
dropout:
  value: 1.3927410805918268
epoch:
  value: 15
epochs:
  value: 17
initial_learning_rate:
  value: 1.4508694612174925e-06
layer_1:
  value: 814
layer_2:
  value: 16
learning_rate:
  value: 0.0018874800425125048
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001362354720101156
optimizer:
  value: sgd
patience:
  value: 8
random_seed:
  value: 67
staircase:
  value: 'true'
validation_split:
  value: 0.24700142652254728
verbose:
  value: 1
