wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 39
conv1_filters:
  value: 12
conv1_kernelsize:
  value: 6
conv2_filters:
  value: 16
conv2_kernelsize:
  value: 4
decay_rate:
  value: 0.48820767118765673
decay_steps:
  value: 190
dense1_size:
  value: 96
dropout:
  value: 0.7751956583702331
epoch:
  value: 14
epochs:
  value: 6
initial_learning_rate:
  value: 5.099671744091502e-07
layer_1:
  value: 540
layer_2:
  value: 10
learning_rate:
  value: 0.0012600904884213782
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0015202616018302943
optimizer:
  value: sgd
patience:
  value: 5
random_seed:
  value: 80
staircase:
  value: 'true'
validation_split:
  value: 0.30832961886006893
verbose:
  value: 2
