wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 60
conv1_filters:
  value: 16
conv1_kernelsize:
  value: 6
conv2_filters:
  value: 23
conv2_kernelsize:
  value: 4
decay_rate:
  value: 0.42758738438568256
decay_steps:
  value: 447
dense1_size:
  value: 80
dropout:
  value: 1.0810361459611744
epoch:
  value: 14
epochs:
  value: 5
initial_learning_rate:
  value: 1.257704324504416e-06
layer_1:
  value: 304
layer_2:
  value: 9
learning_rate:
  value: 0.001783087362660728
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0013533824035677983
optimizer:
  value: sgd
patience:
  value: 8
random_seed:
  value: 71
staircase:
  value: 'false'
validation_split:
  value: 0.3141977533073528
verbose:
  value: 2
