wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 38
conv1_filters:
  value: 11
conv1_kernelsize:
  value: 3
conv2_filters:
  value: 30
conv2_kernelsize:
  value: 6
decay_rate:
  value: 0.742036861795294
decay_steps:
  value: 538
dense1_size:
  value: 101
dropout:
  value: 0.3270658010310904
epoch:
  value: 10
epochs:
  value: 6
initial_learning_rate:
  value: 1.5449312514266168e-06
layer_1:
  value: 831
layer_2:
  value: 20
learning_rate:
  value: 0.00166938591556177
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0007853422783169845
optimizer:
  value: sgd
patience:
  value: 10
random_seed:
  value: 41
staircase:
  value: 'true'
validation_split:
  value: 0.1444180259679953
verbose:
  value: 2
