wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 39
conv1_filters:
  value: 8
conv1_kernelsize:
  value: 10
conv2_filters:
  value: 12
conv2_kernelsize:
  value: 6
decay_rate:
  value: 0.4864538365825781
decay_steps:
  value: 293
dense1_size:
  value: 76
dropout:
  value: 0.8522826776433562
epoch:
  value: 15
epochs:
  value: 14
initial_learning_rate:
  value: 1.7573091971602208e-06
layer_1:
  value: 779
layer_2:
  value: 8
learning_rate:
  value: 0.0011179225816222143
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0007068176487471213
optimizer:
  value: sgd
patience:
  value: 8
random_seed:
  value: 66
staircase:
  value: 'true'
validation_split:
  value: 0.2851548357250846
verbose:
  value: 1
