wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 16
conv1_filters:
  value: 13
conv1_kernelsize:
  value: 5
conv2_filters:
  value: 21
conv2_kernelsize:
  value: 2
decay_rate:
  value: 0.3743056015598063
decay_steps:
  value: 553
dense1_size:
  value: 90
dropout:
  value: 0.38318362223816527
epoch:
  value: 7
epochs:
  value: 16
initial_learning_rate:
  value: 6.74056883185583e-07
layer_1:
  value: 332
layer_2:
  value: 13
learning_rate:
  value: 0.0018573197412959704
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0010360129924459967
optimizer:
  value: sgd
patience:
  value: 10
random_seed:
  value: 65
staircase:
  value: 'true'
validation_split:
  value: 0.17913922179302072
verbose:
  value: 2
