wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 42
conv1_filters:
  value: 15
conv1_kernelsize:
  value: 4
conv2_filters:
  value: 11
conv2_kernelsize:
  value: 3
decay_rate:
  value: 0.8243890178239952
decay_steps:
  value: 531
dense1_size:
  value: 116
dropout:
  value: 0.5521361638734249
epoch:
  value: 9
epochs:
  value: 13
initial_learning_rate:
  value: 8.674969683746924e-07
layer_1:
  value: 545
layer_2:
  value: 7
learning_rate:
  value: 0.0006719288140083108
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001829871750801241
optimizer:
  value: sgd
patience:
  value: 7
random_seed:
  value: 36
staircase:
  value: 'false'
validation_split:
  value: 0.3778109934422553
verbose:
  value: 1
