wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 26
conv1_filters:
  value: 7
conv1_kernelsize:
  value: 8
conv2_filters:
  value: 12
conv2_kernelsize:
  value: 4
decay_rate:
  value: 0.4418181775024303
decay_steps:
  value: 452
dense1_size:
  value: 59
dropout:
  value: 1.0555358851527512
epoch:
  value: 11
epochs:
  value: 19
initial_learning_rate:
  value: 9.862591402711458e-07
layer_1:
  value: 436
layer_2:
  value: 16
learning_rate:
  value: 0.001612736490042785
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001960471979935578
optimizer:
  value: sgd
patience:
  value: 4
random_seed:
  value: 63
staircase:
  value: 'true'
validation_split:
  value: 0.15931911270938637
verbose:
  value: 1
