wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 52
conv1_filters:
  value: 16
conv1_kernelsize:
  value: 5
conv2_filters:
  value: 27
conv2_kernelsize:
  value: 5
decay_rate:
  value: 0.5778227161675765
decay_steps:
  value: 575
dense1_size:
  value: 110
dropout:
  value: 0.4695969505212604
epoch:
  value: 7
epochs:
  value: 18
initial_learning_rate:
  value: 1.7157430231076378e-06
layer_1:
  value: 358
layer_2:
  value: 8
learning_rate:
  value: 0.0019991082369285942
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0006230995243106947
optimizer:
  value: sgd
patience:
  value: 10
random_seed:
  value: 79
staircase:
  value: 'true'
validation_split:
  value: 0.23237576619980557
verbose:
  value: 2
