wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 34
conv1_filters:
  value: 16
conv1_kernelsize:
  value: 3
conv2_filters:
  value: 30
conv2_kernelsize:
  value: 3
decay_rate:
  value: 0.987081735956542
decay_steps:
  value: 455
dense1_size:
  value: 113
dropout:
  value: 0.45551111699810864
epoch:
  value: 10
epochs:
  value: 18
initial_learning_rate:
  value: 1.5148473225246342e-06
layer_1:
  value: 965
layer_2:
  value: 8
learning_rate:
  value: 0.0010448257178457352
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0010367886986122675
optimizer:
  value: sgd
patience:
  value: 10
random_seed:
  value: 36
staircase:
  value: 'true'
validation_split:
  value: 0.3943763692294346
verbose:
  value: 2
