wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 44
conv1_filters:
  value: 5
conv1_kernelsize:
  value: 10
conv2_filters:
  value: 19
conv2_kernelsize:
  value: 6
decay_rate:
  value: 0.8010697110603013
decay_steps:
  value: 375
dense1_size:
  value: 43
dropout:
  value: 1.25166923796019
epoch:
  value: 16
epochs:
  value: 14
initial_learning_rate:
  value: 1.8446428377179e-06
layer_1:
  value: 463
layer_2:
  value: 18
learning_rate:
  value: 0.001075470561337861
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0006324011415192141
optimizer:
  value: sgd
patience:
  value: 10
random_seed:
  value: 45
staircase:
  value: 'false'
validation_split:
  value: 0.19087986927236664
verbose:
  value: 1
