wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 19
conv1_filters:
  value: 12
conv1_kernelsize:
  value: 9
conv2_filters:
  value: 28
conv2_kernelsize:
  value: 2
decay_rate:
  value: 0.5744666039387225
decay_steps:
  value: 543
dense1_size:
  value: 112
dropout:
  value: 0.9745324620348008
epoch:
  value: 9
epochs:
  value: 11
initial_learning_rate:
  value: 1.2919045546827734e-06
layer_1:
  value: 913
layer_2:
  value: 7
learning_rate:
  value: 0.0010754342672412535
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0010342282642460431
optimizer:
  value: sgd
patience:
  value: 4
random_seed:
  value: 60
staircase:
  value: 'false'
validation_split:
  value: 0.1238313358132438
verbose:
  value: 1
