wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 38
conv1_filters:
  value: 11
conv1_kernelsize:
  value: 7
conv2_filters:
  value: 11
conv2_kernelsize:
  value: 6
decay_rate:
  value: 0.43164769212649134
decay_steps:
  value: 533
dense1_size:
  value: 61
dropout:
  value: 0.7838377860862981
epoch:
  value: 7
epochs:
  value: 17
initial_learning_rate:
  value: 1.0757958254558189e-06
layer_1:
  value: 1014
layer_2:
  value: 5
learning_rate:
  value: 0.0007051545241076324
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0006350706132481136
optimizer:
  value: sgd
patience:
  value: 6
random_seed:
  value: 70
staircase:
  value: 'false'
validation_split:
  value: 0.19123870330318393
verbose:
  value: 1
