wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 31
conv1_filters:
  value: 5
conv1_kernelsize:
  value: 4
conv2_filters:
  value: 12
conv2_kernelsize:
  value: 6
decay_rate:
  value: 0.9260678227507526
decay_steps:
  value: 331
dense1_size:
  value: 90
dropout:
  value: 0.3090079899750008
epoch:
  value: 14
epochs:
  value: 12
initial_learning_rate:
  value: 1.250950231092576e-06
layer_1:
  value: 533
layer_2:
  value: 20
learning_rate:
  value: 0.0013597368095081578
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001156251434619655
optimizer:
  value: sgd
patience:
  value: 8
random_seed:
  value: 27
staircase:
  value: 'true'
validation_split:
  value: 0.3313731022959441
verbose:
  value: 1
