wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 22
conv1_filters:
  value: 5
conv1_kernelsize:
  value: 10
conv2_filters:
  value: 17
conv2_kernelsize:
  value: 2
decay_rate:
  value: 0.3379765097520034
decay_steps:
  value: 521
dense1_size:
  value: 96
dropout:
  value: 0.8144713115040212
epoch:
  value: 12
epochs:
  value: 14
initial_learning_rate:
  value: 7.281004976182354e-07
layer_1:
  value: 547
layer_2:
  value: 11
learning_rate:
  value: 0.001089803602184856
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0013871205716231925
optimizer:
  value: sgd
patience:
  value: 3
random_seed:
  value: 47
staircase:
  value: 'false'
validation_split:
  value: 0.31280336034632095
verbose:
  value: 1
