wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 51
conv1_filters:
  value: 11
conv1_kernelsize:
  value: 9
conv2_filters:
  value: 30
conv2_kernelsize:
  value: 6
decay_rate:
  value: 0.4034604392978888
decay_steps:
  value: 437
dense1_size:
  value: 41
dropout:
  value: 1.301102175884109
epoch:
  value: 6
epochs:
  value: 20
initial_learning_rate:
  value: 1.817316874715719e-06
layer_1:
  value: 504
layer_2:
  value: 10
learning_rate:
  value: 0.0012194650903034276
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0012502733141784308
optimizer:
  value: sgd
patience:
  value: 5
random_seed:
  value: 79
staircase:
  value: 'false'
validation_split:
  value: 0.19477422885650905
verbose:
  value: 1
