wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 16
conv1_filters:
  value: 14
conv1_kernelsize:
  value: 5
conv2_filters:
  value: 8
conv2_kernelsize:
  value: 5
decay_rate:
  value: 0.28599402035714283
decay_steps:
  value: 448
dense1_size:
  value: 57
dropout:
  value: 0.62911662936681
epoch:
  value: 12
epochs:
  value: 20
initial_learning_rate:
  value: 1.5653986242276058e-06
layer_1:
  value: 348
layer_2:
  value: 5
learning_rate:
  value: 0.0009893119556672065
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0013777878571274332
optimizer:
  value: sgd
patience:
  value: 4
random_seed:
  value: 25
staircase:
  value: 'false'
validation_split:
  value: 0.3676459454061388
verbose:
  value: 2
