wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 20
conv1_filters:
  value: 5
conv1_kernelsize:
  value: 8
conv2_filters:
  value: 27
conv2_kernelsize:
  value: 6
decay_rate:
  value: 0.3760447672736827
decay_steps:
  value: 358
dense1_size:
  value: 109
dropout:
  value: 0.6707622395760066
epoch:
  value: 16
epochs:
  value: 10
initial_learning_rate:
  value: 1.8436069797957856e-06
layer_1:
  value: 791
layer_2:
  value: 16
learning_rate:
  value: 0.0007125640140312603
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001574709107328683
optimizer:
  value: sgd
patience:
  value: 10
random_seed:
  value: 59
staircase:
  value: 'false'
validation_split:
  value: 0.19838895535407727
verbose:
  value: 1
