wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 27
conv1_filters:
  value: 12
conv1_kernelsize:
  value: 4
conv2_filters:
  value: 24
conv2_kernelsize:
  value: 3
decay_rate:
  value: 0.40024504627560425
decay_steps:
  value: 188
dense1_size:
  value: 111
dropout:
  value: 0.6419386768672858
epoch:
  value: 9
epochs:
  value: 15
initial_learning_rate:
  value: 1.1970710108750253e-06
layer_1:
  value: 799
layer_2:
  value: 5
learning_rate:
  value: 0.0014222117845472766
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001152717133791003
optimizer:
  value: sgd
patience:
  value: 8
random_seed:
  value: 44
staircase:
  value: 'true'
validation_split:
  value: 0.2413583445120165
verbose:
  value: 2
