wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 42
conv1_filters:
  value: 10
conv1_kernelsize:
  value: 4
conv2_filters:
  value: 30
conv2_kernelsize:
  value: 4
decay_rate:
  value: 0.3566820347982692
decay_steps:
  value: 241
dense1_size:
  value: 113
dropout:
  value: 0.7549712845342579
epoch:
  value: 14
epochs:
  value: 7
initial_learning_rate:
  value: 6.869488636769355e-07
layer_1:
  value: 396
layer_2:
  value: 6
learning_rate:
  value: 0.0015634236827581603
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0013656352398420603
optimizer:
  value: sgd
patience:
  value: 8
random_seed:
  value: 22
staircase:
  value: 'false'
validation_split:
  value: 0.37972356124037754
verbose:
  value: 2
