wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 39
conv1_filters:
  value: 12
conv1_kernelsize:
  value: 9
conv2_filters:
  value: 8
conv2_kernelsize:
  value: 4
decay_rate:
  value: 0.33219354245645394
decay_steps:
  value: 519
dense1_size:
  value: 98
dropout:
  value: 0.7407028706733899
epoch:
  value: 10
epochs:
  value: 17
initial_learning_rate:
  value: 5.120126142999573e-07
layer_1:
  value: 297
layer_2:
  value: 11
learning_rate:
  value: 0.0008350717785772714
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0011278155105359814
optimizer:
  value: sgd
patience:
  value: 6
random_seed:
  value: 78
staircase:
  value: 'false'
validation_split:
  value: 0.270125544447711
verbose:
  value: 2
