wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 64
conv1_filters:
  value: 14
conv1_kernelsize:
  value: 7
conv2_filters:
  value: 28
conv2_kernelsize:
  value: 3
decay_rate:
  value: 0.9423967673607708
decay_steps:
  value: 183
dense1_size:
  value: 64
dropout:
  value: 1.1181173265970814
epoch:
  value: 11
epochs:
  value: 6
initial_learning_rate:
  value: 7.86171966232646e-07
layer_1:
  value: 574
layer_2:
  value: 7
learning_rate:
  value: 0.001576331262206334
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0016370681970295916
optimizer:
  value: sgd
patience:
  value: 9
random_seed:
  value: 65
staircase:
  value: 'true'
validation_split:
  value: 0.193365656859162
verbose:
  value: 2
