wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 47
conv1_filters:
  value: 9
conv1_kernelsize:
  value: 9
conv2_filters:
  value: 11
conv2_kernelsize:
  value: 4
decay_rate:
  value: 0.32958184073757657
decay_steps:
  value: 222
dense1_size:
  value: 109
dropout:
  value: 0.8343477904725141
epoch:
  value: 8
epochs:
  value: 20
initial_learning_rate:
  value: 1.1766671648011703e-06
layer_1:
  value: 954
layer_2:
  value: 18
learning_rate:
  value: 0.00189133074890161
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0009057371188296652
optimizer:
  value: sgd
patience:
  value: 3
random_seed:
  value: 59
staircase:
  value: 'false'
validation_split:
  value: 0.24326502298821784
verbose:
  value: 2
