wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 48
conv1_filters:
  value: 9
conv1_kernelsize:
  value: 9
conv2_filters:
  value: 24
conv2_kernelsize:
  value: 6
decay_rate:
  value: 0.41769902878075793
decay_steps:
  value: 201
dense1_size:
  value: 87
dropout:
  value: 0.34454961791701766
epoch:
  value: 10
epochs:
  value: 20
initial_learning_rate:
  value: 1.0310566668225557e-06
layer_1:
  value: 425
layer_2:
  value: 14
learning_rate:
  value: 0.001371100158899176
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0010936430169814276
optimizer:
  value: sgd
patience:
  value: 7
random_seed:
  value: 25
staircase:
  value: 'true'
validation_split:
  value: 0.1604976918513607
verbose:
  value: 1
