wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 64
conv1_filters:
  value: 7
conv1_kernelsize:
  value: 4
conv2_filters:
  value: 21
conv2_kernelsize:
  value: 3
decay_rate:
  value: 0.383315068673975
decay_steps:
  value: 428
dense1_size:
  value: 121
dropout:
  value: 0.32909471004440133
epoch:
  value: 4
epochs:
  value: 8
initial_learning_rate:
  value: 6.541202654246812e-07
layer_1:
  value: 561
layer_2:
  value: 15
learning_rate:
  value: 0.0005442646045923804
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0012835460470206877
optimizer:
  value: sgd
patience:
  value: 4
random_seed:
  value: 41
staircase:
  value: 'true'
validation_split:
  value: 0.24957775786736525
verbose:
  value: 2
