wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 31
conv1_filters:
  value: 4
conv1_kernelsize:
  value: 3
conv2_filters:
  value: 22
conv2_kernelsize:
  value: 2
decay_rate:
  value: 0.6364193528262748
decay_steps:
  value: 300
dense1_size:
  value: 116
dropout:
  value: 0.14651087927238612
epoch:
  value: 13
epochs:
  value: 10
initial_learning_rate:
  value: 1.6102726870947036e-06
layer_1:
  value: 696
layer_2:
  value: 10
learning_rate:
  value: 0.0013975876138271025
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001141267457367063
optimizer:
  value: sgd
patience:
  value: 7
random_seed:
  value: 79
staircase:
  value: 'true'
validation_split:
  value: 0.25802383687832714
verbose:
  value: 1
