wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 63
conv1_filters:
  value: 7
conv1_kernelsize:
  value: 8
conv2_filters:
  value: 19
conv2_kernelsize:
  value: 6
decay_rate:
  value: 0.9275060273927483
decay_steps:
  value: 307
dense1_size:
  value: 102
dropout:
  value: 1.26955748143448
epoch:
  value: 6
epochs:
  value: 11
initial_learning_rate:
  value: 1.958898914699242e-06
layer_1:
  value: 441
layer_2:
  value: 7
learning_rate:
  value: 0.000788430071539336
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.000815465778666259
optimizer:
  value: sgd
patience:
  value: 9
random_seed:
  value: 29
staircase:
  value: 'true'
validation_split:
  value: 0.3645555504755043
verbose:
  value: 1
