wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 32
conv1_filters:
  value: 7
conv1_kernelsize:
  value: 6
conv2_filters:
  value: 9
conv2_kernelsize:
  value: 6
decay_rate:
  value: 0.6303724288485218
decay_steps:
  value: 361
dense1_size:
  value: 108
dropout:
  value: 0.36811053513262415
epoch:
  value: 4
epochs:
  value: 5
initial_learning_rate:
  value: 1.129780695254225e-06
layer_1:
  value: 403
layer_2:
  value: 20
learning_rate:
  value: 0.0016225309128204597
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0009314163962082442
optimizer:
  value: sgd
patience:
  value: 10
random_seed:
  value: 42
staircase:
  value: 'true'
validation_split:
  value: 0.3156839800839434
verbose:
  value: 1
