wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 62
conv1_filters:
  value: 11
conv1_kernelsize:
  value: 9
conv2_filters:
  value: 21
conv2_kernelsize:
  value: 5
decay_rate:
  value: 0.2900465386511475
decay_steps:
  value: 473
dense1_size:
  value: 49
dropout:
  value: 1.3715521378568043
epoch:
  value: 16
epochs:
  value: 17
initial_learning_rate:
  value: 7.946163787719026e-07
layer_1:
  value: 469
layer_2:
  value: 5
learning_rate:
  value: 0.0007304299613592524
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.000913559188608586
optimizer:
  value: sgd
patience:
  value: 8
random_seed:
  value: 23
staircase:
  value: 'false'
validation_split:
  value: 0.2650053410155743
verbose:
  value: 2
