wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 56
conv1_filters:
  value: 8
conv1_kernelsize:
  value: 4
conv2_filters:
  value: 15
conv2_kernelsize:
  value: 4
decay_rate:
  value: 0.6849141847930761
decay_steps:
  value: 366
dense1_size:
  value: 100
dropout:
  value: 0.49718310769400975
epoch:
  value: 12
epochs:
  value: 10
initial_learning_rate:
  value: 6.447003859660461e-07
layer_1:
  value: 459
layer_2:
  value: 19
learning_rate:
  value: 0.0012252560033654191
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001443979468884396
optimizer:
  value: sgd
patience:
  value: 3
random_seed:
  value: 52
staircase:
  value: 'false'
validation_split:
  value: 0.16420681665794667
verbose:
  value: 1
