wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 59
conv1_filters:
  value: 11
conv1_kernelsize:
  value: 3
conv2_filters:
  value: 8
conv2_kernelsize:
  value: 5
decay_rate:
  value: 0.2842325086866743
decay_steps:
  value: 371
dense1_size:
  value: 126
dropout:
  value: 1.2220561763947433
epoch:
  value: 11
epochs:
  value: 9
initial_learning_rate:
  value: 1.081098189008303e-06
layer_1:
  value: 826
layer_2:
  value: 18
learning_rate:
  value: 0.001381655787390322
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0008404628160186755
optimizer:
  value: sgd
patience:
  value: 4
random_seed:
  value: 23
staircase:
  value: 'true'
validation_split:
  value: 0.2710570258570555
verbose:
  value: 1
