wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 23
conv1_filters:
  value: 6
conv1_kernelsize:
  value: 10
conv2_filters:
  value: 22
conv2_kernelsize:
  value: 5
decay_rate:
  value: 0.8153903571456986
decay_steps:
  value: 223
dense1_size:
  value: 42
dropout:
  value: 0.8564801839298783
epoch:
  value: 14
epochs:
  value: 11
initial_learning_rate:
  value: 1.7061239115339671e-06
layer_1:
  value: 492
layer_2:
  value: 16
learning_rate:
  value: 0.0005310337483485157
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0013584043578051192
optimizer:
  value: sgd
patience:
  value: 6
random_seed:
  value: 54
staircase:
  value: 'true'
validation_split:
  value: 0.10302793261936796
verbose:
  value: 1
