wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 21
conv1_filters:
  value: 5
conv1_kernelsize:
  value: 3
conv2_filters:
  value: 16
conv2_kernelsize:
  value: 4
decay_rate:
  value: 0.44104255099215495
decay_steps:
  value: 223
dense1_size:
  value: 83
dropout:
  value: 0.17222735233675895
epoch:
  value: 10
epochs:
  value: 9
initial_learning_rate:
  value: 8.070034571076045e-07
layer_1:
  value: 955
layer_2:
  value: 18
learning_rate:
  value: 0.0011865856358986725
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001089515330158915
optimizer:
  value: sgd
patience:
  value: 4
random_seed:
  value: 73
staircase:
  value: 'false'
validation_split:
  value: 0.16114076301162542
verbose:
  value: 2
