wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 34
conv1_filters:
  value: 11
conv1_kernelsize:
  value: 7
conv2_filters:
  value: 8
conv2_kernelsize:
  value: 2
decay_rate:
  value: 0.9009947697550672
decay_steps:
  value: 478
dense1_size:
  value: 119
dropout:
  value: 0.21518187102320815
epoch:
  value: 8
epochs:
  value: 18
initial_learning_rate:
  value: 1.0465486723773036e-06
layer_1:
  value: 324
layer_2:
  value: 19
learning_rate:
  value: 0.0011589976825193528
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0017654299854769962
optimizer:
  value: sgd
patience:
  value: 5
random_seed:
  value: 78
staircase:
  value: 'false'
validation_split:
  value: 0.1959850490741297
verbose:
  value: 1
