wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 24
conv1_filters:
  value: 13
conv1_kernelsize:
  value: 5
conv2_filters:
  value: 22
conv2_kernelsize:
  value: 2
decay_rate:
  value: 0.6937030377162513
decay_steps:
  value: 468
dense1_size:
  value: 58
dropout:
  value: 0.3473953377794129
epoch:
  value: 10
epochs:
  value: 17
initial_learning_rate:
  value: 1.1899793348128605e-06
layer_1:
  value: 589
layer_2:
  value: 12
learning_rate:
  value: 0.0015710689519393523
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0011485236360065515
optimizer:
  value: sgd
patience:
  value: 6
random_seed:
  value: 45
staircase:
  value: 'false'
validation_split:
  value: 0.2749389824513651
verbose:
  value: 1
