wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 32
conv1_filters:
  value: 12
conv1_kernelsize:
  value: 5
conv2_filters:
  value: 24
conv2_kernelsize:
  value: 3
decay_rate:
  value: 0.3391952864480516
decay_steps:
  value: 297
dense1_size:
  value: 80
dropout:
  value: 0.8587560426888947
epoch:
  value: 6
epochs:
  value: 12
initial_learning_rate:
  value: 1.6196857437601422e-06
layer_1:
  value: 275
layer_2:
  value: 15
learning_rate:
  value: 0.001544512621507787
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0006415729830327161
optimizer:
  value: sgd
patience:
  value: 10
random_seed:
  value: 45
staircase:
  value: 'true'
validation_split:
  value: 0.23584614455478303
verbose:
  value: 2
