wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 39
conv1_filters:
  value: 12
conv1_kernelsize:
  value: 10
conv2_filters:
  value: 14
conv2_kernelsize:
  value: 3
decay_rate:
  value: 0.31241596166770735
decay_steps:
  value: 150
dense1_size:
  value: 34
dropout:
  value: 0.8802794326212691
epoch:
  value: 4
epochs:
  value: 8
initial_learning_rate:
  value: 1.872658106627068e-06
layer_1:
  value: 814
layer_2:
  value: 20
learning_rate:
  value: 0.0017122428383200504
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001913902719045878
optimizer:
  value: sgd
patience:
  value: 4
random_seed:
  value: 31
staircase:
  value: 'false'
validation_split:
  value: 0.144903986548699
verbose:
  value: 2
