wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 64
conv1_filters:
  value: 14
conv1_kernelsize:
  value: 5
conv2_filters:
  value: 13
conv2_kernelsize:
  value: 5
decay_rate:
  value: 0.3339500213180846
decay_steps:
  value: 545
dense1_size:
  value: 75
dropout:
  value: 0.6400605057501036
epoch:
  value: 8
epochs:
  value: 7
initial_learning_rate:
  value: 9.657319829826263e-07
layer_1:
  value: 890
layer_2:
  value: 19
learning_rate:
  value: 0.001199587358366951
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0019129100909231504
optimizer:
  value: sgd
patience:
  value: 5
random_seed:
  value: 22
staircase:
  value: 'false'
validation_split:
  value: 0.200482241953708
verbose:
  value: 1
