wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 31
conv1_filters:
  value: 7
conv1_kernelsize:
  value: 7
conv2_filters:
  value: 11
conv2_kernelsize:
  value: 5
decay_rate:
  value: 0.5722520171746953
decay_steps:
  value: 292
dense1_size:
  value: 68
dropout:
  value: 0.13590864739980704
epoch:
  value: 13
epochs:
  value: 16
initial_learning_rate:
  value: 9.693246894964446e-07
layer_1:
  value: 339
layer_2:
  value: 5
learning_rate:
  value: 0.0016054752055460451
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0013025870120721749
optimizer:
  value: sgd
patience:
  value: 8
random_seed:
  value: 29
staircase:
  value: 'true'
validation_split:
  value: 0.3670939750776083
verbose:
  value: 2
