wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 64
conv1_filters:
  value: 7
conv1_kernelsize:
  value: 5
conv2_filters:
  value: 13
conv2_kernelsize:
  value: 3
decay_rate:
  value: 0.2867406865730122
decay_steps:
  value: 453
dense1_size:
  value: 73
dropout:
  value: 0.2501156015505005
epoch:
  value: 4
epochs:
  value: 17
initial_learning_rate:
  value: 5.209796853399933e-07
layer_1:
  value: 472
layer_2:
  value: 9
learning_rate:
  value: 0.001310481438717111
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0005161198933212554
optimizer:
  value: sgd
patience:
  value: 3
random_seed:
  value: 36
staircase:
  value: 'false'
validation_split:
  value: 0.24912273584370043
verbose:
  value: 2
