wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 34
conv1_filters:
  value: 12
conv1_kernelsize:
  value: 8
conv2_filters:
  value: 27
conv2_kernelsize:
  value: 2
decay_rate:
  value: 0.3746839143646503
decay_steps:
  value: 428
dense1_size:
  value: 45
dropout:
  value: 0.5739815559419037
epoch:
  value: 15
epochs:
  value: 12
initial_learning_rate:
  value: 1.916392347515595e-06
layer_1:
  value: 546
layer_2:
  value: 15
learning_rate:
  value: 0.0016145474984053693
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0007694592142538306
optimizer:
  value: sgd
patience:
  value: 7
random_seed:
  value: 78
staircase:
  value: 'false'
validation_split:
  value: 0.2213164706450189
verbose:
  value: 1
