wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 62
conv1_filters:
  value: 9
conv1_kernelsize:
  value: 9
conv2_filters:
  value: 27
conv2_kernelsize:
  value: 3
decay_rate:
  value: 0.26468110808098844
decay_steps:
  value: 297
dense1_size:
  value: 108
dropout:
  value: 0.3931113888078913
epoch:
  value: 8
epochs:
  value: 16
initial_learning_rate:
  value: 1.4448835480142208e-06
layer_1:
  value: 801
layer_2:
  value: 10
learning_rate:
  value: 0.000788529310532274
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0019171022630562252
optimizer:
  value: sgd
patience:
  value: 4
random_seed:
  value: 39
staircase:
  value: 'false'
validation_split:
  value: 0.3401707170724998
verbose:
  value: 2
