wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 61
conv1_filters:
  value: 9
conv1_kernelsize:
  value: 10
conv2_filters:
  value: 29
conv2_kernelsize:
  value: 3
decay_rate:
  value: 0.929835016738916
decay_steps:
  value: 595
dense1_size:
  value: 61
dropout:
  value: 0.3841595757362505
epoch:
  value: 9
epochs:
  value: 15
initial_learning_rate:
  value: 1.993404745421388e-06
layer_1:
  value: 478
layer_2:
  value: 18
learning_rate:
  value: 0.0013038567951818695
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0018449927717629016
optimizer:
  value: sgd
patience:
  value: 4
random_seed:
  value: 63
staircase:
  value: 'false'
validation_split:
  value: 0.2561941768118397
verbose:
  value: 2
