wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 36
conv1_filters:
  value: 9
conv1_kernelsize:
  value: 9
conv2_filters:
  value: 23
conv2_kernelsize:
  value: 4
decay_rate:
  value: 0.6270456224595845
decay_steps:
  value: 346
dense1_size:
  value: 106
dropout:
  value: 1.1674891673148056
epoch:
  value: 15
epochs:
  value: 7
initial_learning_rate:
  value: 1.08532993303788e-06
layer_1:
  value: 1002
layer_2:
  value: 14
learning_rate:
  value: 0.0009511702819725478
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0005824879906559039
optimizer:
  value: sgd
patience:
  value: 3
random_seed:
  value: 26
staircase:
  value: 'true'
validation_split:
  value: 0.1789660944211517
verbose:
  value: 2
