wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 47
conv1_filters:
  value: 8
conv1_kernelsize:
  value: 3
conv2_filters:
  value: 19
conv2_kernelsize:
  value: 6
decay_rate:
  value: 0.35834403818553695
decay_steps:
  value: 265
dense1_size:
  value: 59
dropout:
  value: 0.43728330793525194
epoch:
  value: 13
epochs:
  value: 15
initial_learning_rate:
  value: 1.518680476979629e-06
layer_1:
  value: 914
layer_2:
  value: 18
learning_rate:
  value: 0.001465634765644238
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0016488266352742405
optimizer:
  value: sgd
patience:
  value: 3
random_seed:
  value: 74
staircase:
  value: 'false'
validation_split:
  value: 0.11030183487920514
verbose:
  value: 1
