wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 29
conv1_filters:
  value: 11
conv1_kernelsize:
  value: 3
conv2_filters:
  value: 27
conv2_kernelsize:
  value: 3
decay_rate:
  value: 0.70185228558909
decay_steps:
  value: 573
dense1_size:
  value: 97
dropout:
  value: 0.6703732193072802
epoch:
  value: 11
epochs:
  value: 5
initial_learning_rate:
  value: 9.879775988162094e-07
layer_1:
  value: 702
layer_2:
  value: 5
learning_rate:
  value: 0.0010686503444829853
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0008563996482913005
optimizer:
  value: sgd
patience:
  value: 10
random_seed:
  value: 83
staircase:
  value: 'false'
validation_split:
  value: 0.33800275295849125
verbose:
  value: 1
