wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 35
conv1_filters:
  value: 4
conv1_kernelsize:
  value: 3
conv2_filters:
  value: 24
conv2_kernelsize:
  value: 2
decay_rate:
  value: 0.8380052126547577
decay_steps:
  value: 248
dense1_size:
  value: 47
dropout:
  value: 0.30015261839181284
epoch:
  value: 12
epochs:
  value: 16
initial_learning_rate:
  value: 1.7967079625389069e-06
layer_1:
  value: 782
layer_2:
  value: 19
learning_rate:
  value: 0.0013971186310142646
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0013655522246624567
optimizer:
  value: sgd
patience:
  value: 10
random_seed:
  value: 53
staircase:
  value: 'false'
validation_split:
  value: 0.33041736157406
verbose:
  value: 1
