wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 19
conv1_filters:
  value: 9
conv1_kernelsize:
  value: 6
conv2_filters:
  value: 14
conv2_kernelsize:
  value: 5
decay_rate:
  value: 0.6898426715151234
decay_steps:
  value: 204
dense1_size:
  value: 47
dropout:
  value: 1.0817916486279946
epoch:
  value: 8
epochs:
  value: 5
initial_learning_rate:
  value: 1.579904754732778e-06
layer_1:
  value: 379
layer_2:
  value: 12
learning_rate:
  value: 0.0019034445786904697
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001778176754763293
optimizer:
  value: sgd
patience:
  value: 10
random_seed:
  value: 46
staircase:
  value: 'false'
validation_split:
  value: 0.2237186108828088
verbose:
  value: 2
