wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 39
conv1_filters:
  value: 8
conv1_kernelsize:
  value: 8
conv2_filters:
  value: 24
conv2_kernelsize:
  value: 4
decay_rate:
  value: 0.5309843337413882
decay_steps:
  value: 521
dense1_size:
  value: 39
dropout:
  value: 1.4145202356621036
epoch:
  value: 6
epochs:
  value: 10
initial_learning_rate:
  value: 1.6853836131929407e-06
layer_1:
  value: 1001
layer_2:
  value: 6
learning_rate:
  value: 0.001112075664324325
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0009472394580519032
optimizer:
  value: sgd
patience:
  value: 8
random_seed:
  value: 33
staircase:
  value: 'false'
validation_split:
  value: 0.19574809317920935
verbose:
  value: 2
