wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 33
conv1_filters:
  value: 8
conv1_kernelsize:
  value: 8
conv2_filters:
  value: 11
conv2_kernelsize:
  value: 4
decay_rate:
  value: 0.9578516163373088
decay_steps:
  value: 429
dense1_size:
  value: 40
dropout:
  value: 1.3288017500661529
epoch:
  value: 7
epochs:
  value: 17
initial_learning_rate:
  value: 7.581124723192179e-07
layer_1:
  value: 953
layer_2:
  value: 17
learning_rate:
  value: 0.0009946683418956197
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0008452720384946888
optimizer:
  value: sgd
patience:
  value: 8
random_seed:
  value: 70
staircase:
  value: 'true'
validation_split:
  value: 0.2737950172187384
verbose:
  value: 2
