wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: relu
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 36
conv1_filters:
  value: 6
conv1_kernelsize:
  value: 10
conv2_filters:
  value: 27
conv2_kernelsize:
  value: 6
decay_rate:
  value: 0.3106816162970612
decay_steps:
  value: 542
dense1_size:
  value: 33
dropout:
  value: 0.5499546244320389
epoch:
  value: 15
epochs:
  value: 14
initial_learning_rate:
  value: 1.3785688909666836e-06
layer_1:
  value: 769
layer_2:
  value: 19
learning_rate:
  value: 0.001977379169595816
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0008459629388441137
optimizer:
  value: sgd
patience:
  value: 8
random_seed:
  value: 25
staircase:
  value: 'false'
validation_split:
  value: 0.22433349115464535
verbose:
  value: 1
