wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 50
conv1_filters:
  value: 8
conv1_kernelsize:
  value: 8
conv2_filters:
  value: 31
conv2_kernelsize:
  value: 6
decay_rate:
  value: 0.893277804481625
decay_steps:
  value: 457
dense1_size:
  value: 57
dropout:
  value: 0.23243980800001823
epoch:
  value: 8
epochs:
  value: 13
initial_learning_rate:
  value: 1.2325173067088882e-06
layer_1:
  value: 400
layer_2:
  value: 15
learning_rate:
  value: 0.001952157351059262
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001185446982381003
optimizer:
  value: sgd
patience:
  value: 8
random_seed:
  value: 62
staircase:
  value: 'false'
validation_split:
  value: 0.26146503706390223
verbose:
  value: 2
