wandb_version: 1

activation_1:
  value: relu
activation_2:
  value: softmax
activation_3:
  value: relu
architecture:
  value: CNN
batch_size:
  value: 43
conv1_filters:
  value: 9
conv1_kernelsize:
  value: 6
conv2_filters:
  value: 28
conv2_kernelsize:
  value: 2
decay_rate:
  value: 0.9409952378500558
decay_steps:
  value: 256
dense1_size:
  value: 50
dropout:
  value: 0.29103116952333524
epoch:
  value: 6
epochs:
  value: 20
initial_learning_rate:
  value: 6.255510574195021e-07
layer_1:
  value: 856
layer_2:
  value: 17
learning_rate:
  value: 0.0009913218897952057
log_freq:
  value: 2
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.001360143570418825
optimizer:
  value: sgd
patience:
  value: 9
random_seed:
  value: 74
staircase:
  value: 'false'
validation_split:
  value: 0.23549890065343235
verbose:
  value: 2
