wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: batch/batch_step
      6:
      - 3
    - 1: batch/loss
      5: 1
      6:
      - 1
    - 1: batch/accuracy
      5: 1
      6:
      - 1
    - 1: batch/learning_rate
      5: 1
      6:
      - 1
    python_version: 3.9.6
    start_time: 1672900843.741804
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 7
      - 23
      - 37
      - 38
      - 39
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_1:
  desc: null
  value: relu
activation_2:
  desc: null
  value: relu
activation_3:
  desc: null
  value: relu
architecture:
  desc: null
  value: CNN
batch_size:
  desc: null
  value: 44
conv1_filters:
  desc: null
  value: 13
conv1_kernelsize:
  desc: null
  value: 3
conv2_filters:
  desc: null
  value: 32
conv2_kernelsize:
  desc: null
  value: 6
decay_rate:
  desc: null
  value: 0.940983057102694
decay_steps:
  desc: null
  value: 157
dense1_size:
  desc: null
  value: 38
dropout:
  desc: null
  value: 0.606792767081798
epoch:
  desc: null
  value: 6
epochs:
  desc: null
  value: 18
initial_learning_rate:
  desc: null
  value: 1.4578798872464945e-06
layer_1:
  desc: null
  value: 863
layer_2:
  desc: null
  value: 17
learning_rate:
  desc: null
  value: 0.0009779934637765774
log_freq:
  desc: null
  value: 2
loss:
  desc: null
  value: mean_squared_error
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.0006903331781015821
optimizer:
  desc: null
  value: sgd
patience:
  desc: null
  value: 4
random_seed:
  desc: null
  value: 56
staircase:
  desc: null
  value: 'false'
validation_split:
  desc: null
  value: 0.28294073811421905
verbose:
  desc: null
  value: 1
