wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.7
    framework: keras
    is_jupyter_run: false
    is_kaggle_kernel: false
    m:
    - 1: batch/batch_step
      6:
      - 3
    - 1: batch/loss
      5: 1
      6:
      - 1
    - 1: batch/accuracy
      5: 1
      6:
      - 1
    - 1: batch/learning_rate
      5: 1
      6:
      - 1
    python_version: 3.9.6
    start_time: 1672942937.591611
    t:
      1:
      - 2
      - 3
      - 55
      2:
      - 2
      - 3
      - 55
      3:
      - 2
      - 7
      - 23
      - 37
      - 38
      - 39
      4: 3.9.6
      5: 0.13.7
      8:
      - 3
      - 5
activation_3:
  desc: null
  value: relu
activation_4:
  desc: null
  value: relu
batch_size:
  desc: null
  value: 21
decay_rate:
  desc: null
  value: 0.557416454212084
decay_steps:
  desc: null
  value: 487
dense1_size:
  desc: null
  value: 110
dense2_size:
  desc: null
  value: 19
dropout:
  desc: null
  value: 0.3961737776491735
epoch:
  desc: null
  value: 10
initial_learning_rate:
  desc: null
  value: 0.0017965066920521391
log_freq:
  desc: null
  value: 2
loss:
  desc: null
  value: categorical_crossentropy
metric:
  desc: null
  value: accuracy
min_delta:
  desc: null
  value: 0.0009731815200106654
optimizer:
  desc: null
  value: adam
patience:
  desc: null
  value: 5
random_seed:
  desc: null
  value: 52
staircase:
  desc: null
  value: 'false'
validation_split:
  desc: null
  value: 0.163396582993137
verbose:
  desc: null
  value: 1
