wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 44
decay_rate:
  value: 0.44266030365817977
decay_steps:
  value: 337
dense1_size:
  value: 72
dense2_size:
  value: 40
dropout:
  value: 0.2853627421201912
epoch:
  value: 14
initial_learning_rate:
  value: 1.015328736857631e-06
log_freq:
  value: 1
loss:
  value: mean_squared_error
metric:
  value: accuracy
min_delta:
  value: 0.0013486902731515587
optimizer:
  value: sgd
patience:
  value: 10
staircase:
  value: 'true'
validation_split:
  value: 0.2020257150152932
verbose:
  value: 1
