wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 23
decay_rate:
  value: 0.2736669054772215
decay_steps:
  value: 380
dense1_size:
  value: 39
dense2_size:
  value: 21
dropout:
  value: 0.331126306798028
epoch:
  value: 6
initial_learning_rate:
  value: 1.527859172671906e-06
log_freq:
  value: 1
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.001327988963959768
optimizer:
  value: sgd
patience:
  value: 3
staircase:
  value: 'false'
validation_split:
  value: 0.32667230009759207
verbose:
  value: 2
