wandb_version: 1

activation_3:
  value: relu
activation_4:
  value: relu
batch_size:
  value: 35
decay_rate:
  value: 0.8280988859777477
decay_steps:
  value: 239
dense1_size:
  value: 70
dense2_size:
  value: 53
dropout:
  value: 0.1872674471861172
epoch:
  value: 4
initial_learning_rate:
  value: 1.0500193795536188e-06
log_freq:
  value: 1
loss:
  value: categorical_crossentropy
metric:
  value: accuracy
min_delta:
  value: 0.0005900891916749663
optimizer:
  value: sgd
patience:
  value: 7
staircase:
  value: 'false'
validation_split:
  value: 0.29603498330702227
verbose:
  value: 1
